In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("res_dataset_cars.csv")
df

,name,price,year,mileage,specs,city,seller,link
0,Skoda Octavia IV (A8),2070000,2022,49900,"['1.4 л, 150 л.с., бензин', 'Лифтбек', 'Передн...",Москва,GROMOV IMPORT,https://auto.ru/cars/used/sale/skoda/octavia/1...
1,Hyundai Solaris II,953700,2018,158735,"['1.6 л, 123 л.с., бензин', 'Седан', 'Передний...",Москва,АО Банк Инго,https://auto.ru/cars/used/sale/hyundai/solaris...
2,Mercedes-Benz V-Класс Extra Long 300 d экстра ...,46850000,2024,100,"['2.0 л, 237 л.с., дизель', 'Минивэн', 'Полный...",Москва,А1 АВТО,https://auto.ru/cars/used/sale/mercedes/v_klas...
3,BMW X5 48i II (E70),550000,2007,220000,"['4.8 л, 355 л.с., бензин', 'Внедорожник 5 дв....",Москва,Irvineflora,https://auto.ru/cars/used/sale/bmw/x5/11018933...
4,Lada (ВАЗ) Kalina I,200000,2006,150000,"['1.6 л, 81 л.с., бензин', 'Седан', 'Передний ...",Москва,петр л.,https://auto.ru/cars/used/sale/vaz/kalina/1131...
...,...,...,...,...,...,...,...,...
12623,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),2021400,2026,_,"['1.8 л, 122 л.с., бензин', 'Универсал 5 дв.',...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/24069...
12624,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),1890000,2026,_,"['1.6 л, 106 л.с., бензин', 'Универсал 5 дв.',...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/23628...
12625,Lada (ВАЗ) Largus I Рестайлинг,1341600,2026,_,"['1.6 л, 90 л.с., бензин', 'Универсал 5 дв.', ...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/largus/2274...
12626,Volkswagen Tiguan Allspace II Рестайлинг,2742000,2022,34000,"['1.5 л, 150 л.с., бензин', 'Внедорожник 5 дв....",Псков,Станислав Игоревич,https://auto.ru/cars/used/sale/volkswagen/tigu...
12627,Lada (ВАЗ) Granta I Рестайлинг,1048000,2026,_,"['1.6 л, 106 л.с., бензин', 'Седан', 'Передний...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/granta/2137...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12628 entries, 0 to 12627
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     12628 non-null  object
 1   price    12628 non-null  int64
 2   year     12628 non-null  int64
 3   mileage  12628 non-null  object
 4   specs    12628 non-null  object
 5   city     12628 non-null  object
 6   seller   12628 non-null  object
 7   link     12628 non-null  object
dtypes: int64(2), object(6)
memory usage: 789.4+ KB

In [ ]:
cities = df['city']
cities = cities.unique()
print(len(cities))
cities

560

array(['Москва', 'Немчиновка', 'Химки', 'Балашиха', 'Пушкино',
       'Красногорск', 'Люберцы', 'Одинцово', 'Зеленоград', 'Коммунарка',
       'Дубна', 'Раменское', 'Обнинск', 'Звенигород', 'Нахабино',
       'Электроугли', 'Королёв', 'Тула', 'Маково', 'Серпухов',
       'Павловский Посад', 'Гагарин', 'Всеволодово', 'Сергиев Посад',
       'Михнево', 'Владимир', 'Тверь', 'Ногинск', 'Домодедово',
       'Подольск', 'Лунёво', 'Рязань', 'Котельники', 'Власиха', 'Жуковка',
       'Егорьевск', 'Дубовая Роща', 'Бронницы', 'Кратово', 'Заречье',
       'Щёлково', 'Долгопрудный', 'Мытищи', 'Раздоры', 'Лобня', 'Видное',
       'Путилково', 'Калуга', 'Поярково', 'Коробово', 'Наро-Фоминск',
       'Онуфриево', 'Городской округ Клин', 'Кубинка', 'Давыдово',
       'Юхнов', 'Железнодорожный', 'Новомосковск', 'Апрелевка',
       'деревня Барвиха', 'Голицыно', 'Электросталь', 'Истра',
       'Ивантеевка', 'Одинцовский район', 'Электрогорск', 'Солнечногорск',
       'Озёры', 'Лапино', 'Реутов', 'Орехово-Зуево', 'Коломна',
       'Лыткарино', 'Чехов', 'Юдино', 'Новоивановское', 'Алексино',
       'Фрязино', 'Щербинка', 'Жуковский', 'Ильинское-Усово', 'Лешково',
       'Щёлковский район', 'Дедовск', 'Луховицы', 'Дзержинский', 'Цибино',
       'Марфино', 'Гусь-Хрустальный', 'Шемякино', 'Шатура', 'Вешки',
       'Жаворонки', 'Городской округ Красногорск', 'Малоярославец',
       'Яхрома', 'Москва и Московская область', 'Владивосток', 'Ржавки',
       'Лопатино', 'Александров', 'Волоколамск', 'Верхнее Мячково',
       'Северный', 'Верея', 'Руза', 'Переславль-Залесский', 'Маринки',
       'Можайск', 'Посёлок завода Мосрентген', 'Троицк', 'Сухарево',
       'Газопровод', 'Отрадное', 'Шолохово', 'Ступино',
       'Серебряные Пруды', 'Северо-Западный административный округ',
       'Дмитров', 'Перепечино', 'Горки-10', 'Шопино', 'Голубое', 'Зубцов',
       'Павловское', 'Шаховская', 'Солнцево', 'Кострома', 'Ярославль',
       'Рыбинск', 'Иваново', 'Торжок', 'Муром', 'Спас-Деменск',
       'Камешково', 'Коляново', 'Мстёра', 'Выкса', 'Чернь', 'Ковров',
       'Мценск', 'Тейково', 'Ржев', 'Ульяново', 'Данилов', 'Удомля',
       'Бурмакино', 'Кохма', 'Приволжск', 'Вышний Волочёк', 'Ефремов',
       'Гусь-Железный', 'Нерехта', 'Данков', 'Белёв', 'Ряжск', 'Оленино',
       'Нововязники', 'Фурманов', 'Богородицк', 'Тутаев', 'Гороховец',
       'Арсеньево', 'Вичуга', 'Орёл', 'Козельск', 'Касимов',
       'Некрасовское', 'Вязьма', 'Мышкин', 'Людиново', 'Киреевск',
       'Сафоново', 'Красное-на-Волге', 'Белый', 'Бологое', 'Навашино',
       'Киров', 'Лев Толстой', 'Сасово', 'Архиповка', 'Шайковка', 'Шуя',
       'Ивановская область', 'Осташков', 'Меленки', 'Вязники',
       'Волгореченск', 'Сухиничи', 'Лежнево', 'Бежецк', 'Петрово',
       'Кувшиново', 'Ново-Талицы', 'Скопин', 'Фанерник', 'Пришня', 'Угра',
       'Ельня', 'Старожилово', 'Зарубино', 'Пителино', 'Милославское',
       'Комсомольск', 'Южа', 'Одоев', 'Ленинский район', 'Мошок',
       'Патакино', 'Мелехово', 'Палех', 'Бегоулево', 'Судогда',
       'Чаплыгин', 'Пожилино', 'Товарковский', 'Новомичуринск',
       'Спасск-Рязанский', 'Новосибирск', 'Самара', 'Томск',
       'Заковряжино', 'Воеводское', 'Камень-на-Оби', 'Барнаул', 'Бердск',
       'Каргасок', 'Горный', 'Кемерово', 'Новокузнецк', 'Ачинск',
       'Барышево', 'Краснобродский', 'Центральный', 'Мыски', 'Киселёвск',
       'Юрга', 'Купино', 'Тальменка', 'Парабель', 'Татарск',
       'Ленинск-Кузнецкий', 'Республика Алтай', 'Тогучин',
       'Анжеро-Судженск', 'Междуреченск', 'Барабинск',
       'Новосибирский район', 'Северск', 'Белово', 'Томская область',
       'Прокопьевск', 'Яшкино', 'Бийск', 'Рубцовск', 'Полысаево',
       'Ордынское', 'Горно-Алтайск', 'Двуречье', 'Алтайское', 'Карасук',
       'Колпашево', 'Озерки', 'Златоуст', 'Новоалтайск', 'Южный',
       'Зоркальцево', 'Топки', 'Алтайский край', 'Кемеровский район',
       'Жемчужный', 'Искитим', 'Смоленское', 'Назарово', 'Павловск',
       'Тяжинский', 'Яровое', 'Новолуговое', 'Веселовское', 'Маслянино',
       'Дубинино', 'Советский район', 'Абаза', 'Салаир', 'Шарыпово',
       'Сибирский', 'Боготол', 'Краснозёрское', 'Старобелокуриха',
       'Белокуриха', 'Акимовка', 'Краснообск', 'Ордынский район',
       'Алейск', 'Шира', 'Славгород', 'Кольцово', 'Благовещенка', 'Чемал',
       'Таштагол', 'Кривошеино', 'Асино', 'Ужур', 'Налобиха', 'Ишим',
       'Мошково', 'Сростки', 'Черепаново', 'Кисловка', 'Завьялово',
       'Павлодар', 'Кулунда', 'Гурьевск', 'Волчиха', 'Крапивинский',
       'Майма', 'Линёво', 'Болотное', 'Куйбышев', 'Чарышское', 'Убинское',
       'Зональная станция', 'Прокудское', 'Заринск', 'Криводановка',
       'Баган', 'Копьёво', 'Осинники', 'Мельниково', 'Мироновка',
       'Дорогино', 'Верх-Чуманка', 'Среднесибирский', 'Чаны', 'Сорск',
       'Утянка', 'Толмачёво', 'Романово', 'Крутиха', 'Аскиз', 'Тисуль',
       'Каменка', 'Новосафоновский', 'Кызыл-Озёк', 'Яркуль',
       'Бельтирское', 'Кыштовка', 'Довольное', 'Медведское', 'Обь',
       'Онгудай', 'Абакан', 'Элитный', 'Троицкое',
       'Городской округ Барнаул', 'Зудилово', 'Загорский',
       'Искитимский район', 'Шебалино', 'Алтайский район', 'Чистоозерное',
       'Александровское', 'Каховка', 'Поспелиха', 'Верх-Кучук',
       'Станция Мочище', 'Мошковский район', 'Усть-Кан', 'Ларичиха',
       'Глядень', 'Кирзинское', 'Октябрьский', 'Ужурский район',
       'Коченёво', 'Вершинино', 'Михайловское', 'Зеленогорский',
       'Черногорск', 'Калачинск', 'Минусинск', 'Черлак', 'Курчатов',
       'Саяногорск', 'Кормиловка', 'Козулька', 'Макеевка', 'Шушенское',
       'Белый Яр', 'Усть-Кокса', 'Морозовка', 'Мульта', 'Ростовка',
       'Большие Сыры', 'Красноярск', 'Большеречье', 'Тара',
       'Усть-Коксинский район', 'Русская Поляна', 'Усть-Абакан', 'Иня',
       'Балахта', 'Усть-Каменогорск', 'Улаган', 'Черёмушки', 'Расцвет',
       'Идринское', 'Семей', 'Курай', 'Таврическое', 'Знаменское',
       'Новочернореченский', 'Харламово', 'Воскресенка', 'Солнечное',
       'Анаш', 'Усть-Заостровка', 'Тесь', 'Оконешниково', 'Ачаирский',
       'Омск', 'Краснотуранск', 'Боград', 'Новомосковка', 'Бея',
       'Павлодарская область', 'Новосёлово', 'Междуречье',
       'Большой Атмас', 'Первомайское', 'Зеленый Бор', 'Павлоградка',
       'Катанда', 'Орлово', 'Омский', 'Богословка', 'Новокурск',
       'Лугавское', 'Большегривское', 'Сыропятское', 'Калинино',
       'Пировское', 'Прииртышье', 'Новороссийка', 'Шунеры', 'Кызыл',
       'Нововаршавка', 'Андреевка', 'Санкт-Петербург', 'Красное Село',
       'Сестрорецк', 'Ропша', 'Репино', 'Рощино', 'Сосновый Бор',
       'Всеволожск', 'Выборг', 'Ягодное', 'Пушкин', 'Гдов',
       'Новосаратовка', 'Шушары', 'Московский район', 'Кингисепп',
       'Энколово', 'Янино-1', 'Ульяновка', 'Стрельна', 'Мурино',
       'Сосново', 'Великий Новгород', 'Луга', 'Порошкино', 'Агалатово',
       'Сортавала', 'Разметелево', 'Гатчина', 'Колпино', 'Кириши',
       'Сланцы', 'Сертолово', 'Тихвин', 'Ковалёво', 'Петергоф',
       'Синявино', 'Волхов', 'Вырица', 'Кудрово', 'Парголово',
       'Кронштадт', 'Щеглово', 'Посёлок имени Свердлова', 'Бугры',
       'Бокситогорск', 'Приладожский', 'Ленинское', 'Чудово',
       'Посёлок имени Морозова', 'Виллозское городское поселение',
       'Тосно', 'Новолисино', 'Новогорелово', 'Новоселицы', 'Питкяранта',
       'Невский округ', 'Ильинский', 'Песочный', 'Лесколово', 'Сясьстрой',
       'Никольское', 'Сапёрный', 'Советский', 'Коммунар', 'Лодейное Поле',
       'Шлиссельбург', 'Малое Карлино', 'Старая', 'Ленсоветовский',
       'Воейково', 'Плюсса', 'Петрозаводск', 'Псков', 'Боровичи',
       'Валдай', 'Пикалево', 'Едрово', 'Чагода', 'Дедовичи', 'Вилга',
       'Вяртсиля', 'Ляскеля', 'Подпорожье', 'Новая Вилга', 'Озёрный',
       'Старая Русса', 'Псковский район', 'Окуловка', 'Печоры', 'Остров',
       'Орел', 'Яжелбицы', 'Выползово', 'Демянск', 'Писковичи', 'Сольцы',
       'Федоровщина', 'Парфино', 'Изборск', 'Городище', 'Порхов',
       'Череха', 'Ваулино', 'Пряжа', 'Любытино', 'Неелово 2-е', 'Дно',
       'Ужесельга', 'Соловьи', 'Рауталахти', 'Бесовец', 'Ладва-Ветка'],
      dtype=object)

In [ ]:
import requests
import json

In [ ]:
import time

In [ ]:
ninja_API = 'Uwi1SFJtGr0E7jkUsjiXwNW60cdQxcYKTx1wr0vH'
geo_API = '066646a31ef941b4703ae590b879a061'
density_API = 'c7cbb8c5f78c44f1b6813438181dfce3'
data = []
import logging
logging.basicConfig(level=logging.INFO, filename='api_logs.log', filemode='w')
logger = logging.getLogger(__name__)
for city in cities:
  logger.info(f'Start making requests for the {city}')
  vowel = {'city':city}
  logger.info(f'Making request of {city} to weather API of longitude and lattitude')
  req_geo = requests.get(f'http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=1&appid={geo_API}', headers={'X-API-KEY':geo_API})
  req_geo.json()
  if len (req_geo.json()) == 0:
    logger.info(f'There is no such city {city} found in weather API')
    continue
  geo = req_geo.json()[0]
  lattitude = geo['lat']
  longitude = geo['lon']
  vowel['lattitude'] = lattitude
  vowel['longitude'] = longitude
  eng_name = geo['name']
  if 'local_names' in geo and 'en' in geo['local_names']:
    eng_name = geo['local_names']['en']
  logger.info(f'Making a request of population of {city} to ninjas API')
  req_city = requests.get(f'https://api.api-ninjas.com/v1/city?name={eng_name}', headers={'X-Api-Key': ninja_API})
  req_city.json()
  if type(req_city.json()) == list and len(req_city.json()) > 0:
    if 'population' in req_city.json()[0]:
      vowel['population'] = req_city.json()[0]['population']
  logger.info(f'Making a request of weather of {city} to weather API')
  req_wheather = requests.get(f'https://api.openweathermap.org/data/2.5/weather?lat={lattitude}&lon={longitude}&units=metric&appid={geo_API}', headers={'X-Api-Key':geo_API})
  req_wheather.json()
  vowel['temperature'] = req_wheather.json()['main']['temp']
  logger.info(f'Making a request of air quality of {city} to weather API')
  req_air = requests.get(f'http://api.openweathermap.org/data/2.5/air_pollution?lat={lattitude}&lon={longitude}&appid={geo_API}', headers={'X-API-KEY':geo_API})
  req_air.json()
  vowel['air_quality'] = req_air.json()['list'][0]['main']['aqi']
  logger.info(f'Making a request of elevation of {city} to meteo API')
  try:
    req_mestnost = requests.get(f'https://api.open-meteo.com/v1/elevation?latitude={lattitude}&longitude={longitude}', timeout=10)
    req_mestnost.json()
    if 'elevation' in req_mestnost.json():
      vowel['mestnost'] = req_mestnost.json()['elevation'][0]
  except:
    logger.info(f'The server of elevation does not respond, skip elevation request for the {city}')
  logger.info(f'Making a request of salary of {city} to head hunter')
  req_salary = requests.get(f'https://api.hh.ru/vacancies?text={city}&only_with_salary=true&per_page=20')
  req_salary.json()
  salary = []
  for elem in req_salary.json()['items']:
    wage = elem['salary']
    if wage != None and wage['currency'] == 'RUR':
      if wage['to'] and wage['from']:
        salary.append((wage['to'] + wage['from']) / 2)
      elif wage['to']:
        salary.append(wage['to'])
      elif wage['from']:
        salary.append(wage['from'])
  if len(salary) != 0:
    vowel['salary'] = sum(salary) / len(salary)
  logger.info(f'Making a request of car infrastructure of {city} to geoapify API')
  req_infrastructure = requests.get(f'https://api.geoapify.com/v2/places?categories=commercial.vehicle,service.vehicle&filter=circle:{longitude},{lattitude},15000&limit=500&apiKey={density_API}', headers={'X-API-KEY':density_API})
  req_infrastructure.json()
  vowel['infrastructure'] = len(req_infrastructure.json()['features'])
  data.append(vowel)
  logger.info(f'All possible data gathered for the {city}')
  time.sleep(0.5)
data

[{'city': 'Москва',
  'lattitude': 55.7504461,
  'longitude': 37.6174943,
  'population': 17125000,
  'temperature': 11.72,
  'air_quality': 2,
  'mestnost': 156.0,
  'salary': 375012.5,
  'infrastructure': 500},
 {'city': 'Немчиновка',
  'lattitude': 55.7208421,
  'longitude': 37.3666309,
  'temperature': 11.9,
  'air_quality': 2,
  'mestnost': 172.0,
  'salary': 141977.15,
  'infrastructure': 500},
 {'city': 'Химки',
  'lattitude': 55.8917293,
  'longitude': 37.4396994,
  'population': 244668,
  'temperature': 10.94,
  'air_quality': 2,
  'mestnost': 186.0,
  'salary': 104605.0,
  'infrastructure': 500},
 {'city': 'Балашиха',
  'lattitude': 55.8036225,
  'longitude': 37.9646488,
  'population': 450771,
  'temperature': 11.26,
  'air_quality': 2,
  'mestnost': 166.0,
  'salary': 107832.5,
  'infrastructure': 500},
 {'city': 'Пушкино',
  'lattitude': 59.722256,
  'longitude': 30.415731,
  'population': 105479,
  'temperature': 10.53,
  'air_quality': 2,
  'mestnost': 44.0,
  'salary': 97655.0,
  'infrastructure': 500},
 {'city': 'Красногорск',
  'lattitude': 55.8217545,
  'longitude': 37.3400897,
  'population': 171793,
  'temperature': 11.57,
  'air_quality': 2,
  'mestnost': 171.0,
  'salary': 96950.0,
  'infrastructure': 500},
 {'city': 'Люберцы',
  'lattitude': 55.6783142,
  'longitude': 37.89377,
  'population': 197705,
  'temperature': 11.21,
  'air_quality': 2,
  'mestnost': 141.0,
  'salary': 128075.0,
  'infrastructure': 500},
 {'city': 'Одинцово',
  'lattitude': 55.6711507,
  'longitude': 37.2727963,
  'population': 140537,
  'temperature': 11.22,
  'air_quality': 2,
  'mestnost': 188.0,
  'salary': 126080.0,
  'infrastructure': 500},
 {'city': 'Зеленоград',
  'lattitude': 55.9964233,
  'longitude': 37.198534,
  'population': 15493,
  'temperature': 10.57,
  'air_quality': 2,
  'mestnost': 233.0,
  'salary': 126650.0,
  'infrastructure': 397},
 {'city': 'Коммунарка',
  'lattitude': 54.382416,
  'longitude': 26.321512,
  'temperature': 11.03,
  'air_quality': 3,
  'mestnost': 248.0,
  'salary': 124000.0,
  'infrastructure': 47},
 {'city': 'Дубна',
  'lattitude': 56.7362705,
  'longitude': 37.1623696,
  'population': 75144,
  'temperature': 10.73,
  'air_quality': 2,
  'mestnost': 118.0,
  'salary': 129985.8,
  'infrastructure': 65},
 {'city': 'Раменское',
  'lattitude': 55.5709361,
  'longitude': 38.2282099,
  'population': 116077,
  'temperature': 10.71,
  'air_quality': 2,
  'mestnost': 119.0,
  'salary': 98050.0,
  'infrastructure': 292},
 {'city': 'Обнинск',
  'lattitude': 55.0951738,
  'longitude': 36.611913,
  'population': 115029,
  'temperature': 9.33,
  'air_quality': 2,
  'mestnost': 174.0,
  'salary': 96381.57894736843,
  'infrastructure': 217},
 {'city': 'Звенигород',
  'lattitude': 55.7293613,
  'longitude': 36.8585382,
  'population': 22513,
  'temperature': 11.21,
  'air_quality': 2,
  'mestnost': 156.0,
  'salary': 104255.0,
  'infrastructure': 99},
 {'city': 'Нахабино',
  'lattitude': 55.8394789,
  'longitude': 37.1770987,
  'temperature': 11.13,
  'air_quality': 2,
  'mestnost': 183.0,
  'salary': 132775.0,
  'infrastructure': 500},
 {'city': 'Электроугли',
  'lattitude': 55.7184467,
  'longitude': 38.2228192,
  'population': 20823,
  'temperature': 11.04,
  'air_quality': 2,
  'mestnost': 151.0,
  'salary': 90097.5,
  'infrastructure': 337},
 {'city': 'Королёв',
  'lattitude': 55.9204898,
  'longitude': 37.8326289,
  'temperature': 11.3,
  'air_quality': 2,
  'mestnost': 167.0,
  'salary': 110406.25,
  'infrastructure': 500},
 {'city': 'Тула',
  'lattitude': 45.2678347,
  'longitude': 1.7706797,
  'temperature': 14.15,
  'air_quality': 2,
  'mestnost': 226.0,
  'salary': 94640.0,
  'infrastructure': 44},
 {'city': 'Маково',
  'lattitude': 41.1187405,
  'longitude': 21.6103212,
  'temperature': 9.84,
  'air_quality': 3,
  'salary': 84166.66666666667,
  'infrastructure': 2},
 {'city': 'Серпухов',
  'lattitude': 54.9155247,
  'longitude': 37.4195533,
  'population': 125817,
  'temperature': 9.65,
  'air_quality': 2,
  'mestnost': 156.0,
  'salary': 93310.0,
  'infrastructure': 148},
 {'city': 'Павловский Посад',
  'lattitude': 55.7813357,
  'longitude': 38.6507838,
  'temperature': 10.91,
  'air_quality': 2,
  'mestnost': 132.0,
  'salary': 89932.0,
  'infrastructure': 224},
 {'city': 'Гагарин',
  'lattitude': 55.553306,
  'longitude': 34.9968416,
  'population': 29041,
  'temperature': 6.1,
  'air_quality': 2,
  'mestnost': 192.0,
  'salary': 182972.22222222222,
  'infrastructure': 22},
 {'city': 'Всеволодово',
  'lattitude': 55.701454,
  'longitude': 38.4808664,
  'temperature': 10.84,
  'air_quality': 2,
  'mestnost': 154.0,
  'salary': 67500.0,
  'infrastructure': 178},
 {'city': 'Сергиев Посад',
  'lattitude': 56.3153529,
  'longitude': 38.1358208,
  'population': 104579,
  'temperature': 10.4,
  'air_quality': 2,
  'mestnost': 230.0,
  'salary': 81901.0,
  'infrastructure': 120},
 {'city': 'Михнево',
  'lattitude': 55.1212335,
  'longitude': 37.9584994,
  'temperature': 10.05,
  'air_quality': 2,
  'mestnost': 183.0,
  'salary': 126873.1,
  'infrastructure': 59},
 {'city': 'Владимир',
  'lattitude': 56.1288899,
  'longitude': 40.4075203,
  'population': 356168,
  'temperature': 7.19,
  'air_quality': 2,
  'mestnost': 152.0,
  'salary': 98394.73684210527,
  'infrastructure': 443},
 {'city': 'Тверь',
  'lattitude': 56.858675,
  'longitude': 35.9208284,
  'population': 419363,
  'temperature': 9.56,
  'air_quality': 2,
  'mestnost': 138.0,
  'salary': 84435.0,
  'infrastructure': 358},
 {'city': 'Ногинск',
  'lattitude': 55.8553511,
  'longitude': 38.4411898,
  'population': 229731,
  'temperature': 11.12,
  'air_quality': 2,
  'salary': 117950.0,
  'infrastructure': 273},
 {'city': 'Домодедово',
  'lattitude': 55.4368213,
  'longitude': 37.7680693,
  'population': 127850,
  'temperature': 10.46,
  'air_quality': 2,
  'mestnost': 161.0,
  'salary': 107423.5,
  'infrastructure': 358},
 {'city': 'Подольск',
  'lattitude': 55.4308841,
  'longitude': 37.5453056,
  'population': 299660,
  'temperature': 10.8,
  'air_quality': 2,
  'mestnost': 157.0,
  'salary': 108037.5,
  'infrastructure': 437},
 {'city': 'Лунёво',
  'lattitude': 56.6144232,
  'longitude': 38.4956995,
  'temperature': 10.38,
  'air_quality': 4,
  'mestnost': 161.0,
  'salary': 66361.8,
  'infrastructure': 6},
 {'city': 'Рязань',
  'lattitude': 54.6295687,
  'longitude': 39.7425039,
  'population': 537622,
  'temperature': 5.24,
  'air_quality': 2,
  'mestnost': 118.0,
  'salary': 104437.5,
  'infrastructure': 341},
 {'city': 'Котельники',
  'lattitude': 55.661668,
  'longitude': 37.8673073,
  'population': 46763,
  'temperature': 11.22,
  'air_quality': 2,
  'mestnost': 149.0,
  'salary': 84942.5,
  'infrastructure': 500},
 {'city': 'Власиха',
  'lattitude': 53.2982076,
  'longitude': 83.5778361,
  'temperature': 0.67,
  'air_quality': 3,
  'mestnost': 181.0,
  'salary': 92532.725,
  'infrastructure': 500},
 {'city': 'Жуковка',
  'lattitude': 55.8681346,
  'longitude': 40.8400235,
  'temperature': 7.69,
  'air_quality': 2,
  'mestnost': 111.0,
  'salary': 154272.5,
  'infrastructure': 18},
 {'city': 'Егорьевск',
  'lattitude': 55.3829765,
  'longitude': 39.0356223,
  'population': 73766,
  'temperature': 9.14,
  'air_quality': 2,
  'mestnost': 148.0,
  'salary': 113674.5,
  'infrastructure': 82},
 {'city': 'Дубовая Роща',
  'lattitude': 54.4805301,
  'longitude': 22.4399827,
  'temperature': 12.16,
  'air_quality': 3,
  'mestnost': 108.0,
  'salary': 63983.333333333336,
  'infrastructure': 2},
 {'city': 'Бронницы',
  'lattitude': 55.4219938,
  'longitude': 38.2590612,
  'population': 22567,
  'temperature': 10.46,
  'air_quality': 2,
  'mestnost': 137.0,
  'salary': 115710.52631578948,
  'infrastructure': 120},
 {'city': 'Кратово',
  'lattitude': 42.079261,
  'longitude': 22.1802182,
  'population': 6924,
  'temperature': 9.1,
  'air_quality': 3,
  'mestnost': 657.0,
  'salary': 92850.0,
  'infrastructure': 5},
 {'city': 'Заречье',
  'lattitude': 55.68776,
  'longitude': 37.3955454,
  'temperature': 12.13,
  'air_quality': 2,
  'mestnost': 173.0,
  'salary': 92875.0,
  'infrastructure': 500},
 {'city': 'Щёлково',
  'lattitude': 55.9206499,
  'longitude': 37.9915576,
  'temperature': 11.51,
  'air_quality': 2,
  'mestnost': 147.0,
  'salary': 107250.0,
  'infrastructure': 500},
 {'city': 'Долгопрудный',
  'lattitude': 55.9341491,
  'longitude': 37.5142417,
  'population': 108861,
  'temperature': 10.85,
  'air_quality': 2,
  'mestnost': 194.0,
  'salary': 69264.0,
  'infrastructure': 500},
 {'city': 'Мытищи',
  'lattitude': 55.9094928,
  'longitude': 37.7339358,
  'population': 205397,
  'temperature': 11.17,
  'air_quality': 2,
  'mestnost': 158.0,
  'salary': 114735.0,
  'infrastructure': 500},
 {'city': 'Раздоры',
  'lattitude': 48.331689,
  'longitude': 35.7132916,
  'temperature': 9.55,
  'air_quality': 3,
  'mestnost': 90.0,
  'salary': 138275.0,
  'infrastructure': 1},
 {'city': 'Лобня',
  'lattitude': 56.0104473,
  'longitude': 37.4670831,
  'population': 88220,
  'temperature': 10.59,
  'air_quality': 2,
  'mestnost': 199.0,
  'salary': 111987.5,
  'infrastructure': 500},
 {'city': 'Видное',
  'lattitude': 55.5571496,
  'longitude': 37.7087142,
  'population': 66158,
  'temperature': 11.04,
  'air_quality': 2,
  'mestnost': 171.0,
  'salary': 97215.95,
  'infrastructure': 500},
 {'city': 'Путилково',
  'lattitude': 55.8625,
  'longitude': 37.390278,
  'temperature': 11.42,
  'air_quality': 2,
  'mestnost': 179.0,
  'salary': 123890.0,
  'infrastructure': 500},
 {'city': 'Калуга',
  'lattitude': 54.5101087,
  'longitude': 36.2598115,
  'population': 341892,
  'temperature': 7.22,
  'air_quality': 2,
  'mestnost': 201.0,
  'salary': 86845.0,
  'infrastructure': 433},
 {'city': 'Поярково',
  'lattitude': 56.0113486,
  'longitude': 37.3311934,
  'temperature': 10.6,
  'air_quality': 2,
  'mestnost': 197.0,
  'salary': 122431.25,
  'infrastructure': 500},
 {'city': 'Коробово',
  'lattitude': 55.8532508,
  'longitude': 40.2117645,
  'temperature': 7.91,
  'air_quality': 3,
  'mestnost': 151.0,
  'salary': 142197.11764705883,
  'infrastructure': 0},
 {'city': 'Наро-Фоминск',
  'lattitude': 55.3879473,
  'longitude': 36.7398309,
  'population': 62002,
  'temperature': 10.31,
  'air_quality': 2,
  'mestnost': 163.0,
  'salary': 94952.5,
  'infrastructure': 89},
 {'city': 'Онуфриево',
  'lattitude': 55.84697505,
  'longitude': 36.49969680889808,
  'temperature': 10.55,
  'air_quality': 2,
  'mestnost': 209.0,
  'salary': 88782.5,
  'infrastructure': 19},
 {'city': 'Кубинка',
  'lattitude': 55.5755486,
  'longitude': 36.6952802,
  'population': 20157,
  'temperature': 10.47,
  'air_quality': 2,
  'mestnost': 210.0,
  'salary': 81512.0,
  'infrastructure': 74},
 {'city': 'Давыдово',
  'lattitude': 55.6078039,
  'longitude': 38.8585305,
  'temperature': 10.12,
  'air_quality': 2,
  'mestnost': 129.0,
  'salary': 91750.0,
  'infrastructure': 22},
 {'city': 'Юхнов',
  'lattitude': 54.7415766,
  'longitude': 35.2264393,
  'temperature': 7.94,
  'air_quality': 2,
  'mestnost': 159.0,
  'salary': 98683.33333333333,
  'infrastructure': 14},
 {'city': 'Железнодорожный',
  'lattitude': 38.5507163,
  'longitude': 68.8305472,
  'temperature': 16.89,
  'air_quality': 3,
  'mestnost': 798.0,
  'salary': 99162.5,
  'infrastructure': 212},
 {'city': 'Новомосковск',
  'lattitude': 48.6358512,
  'longitude': 35.2595541,
  'population': 125647,
  'temperature': 9.49,
  'air_quality': 3,
  'mestnost': 57.0,
  'salary': 108968.42105263157,
  'infrastructure': 120},
 {'city': 'Апрелевка',
  'lattitude': 55.5454306,
  'longitude': 37.0730417,
  'temperature': 10.79,
  'air_quality': 2,
  'mestnost': 198.0,
  'salary': 92297.5,
  'infrastructure': 274},
 {'city': 'Голицыно',
  'lattitude': 55.6149602,
  'longitude': 36.9887625,
  'population': 17651,
  'temperature': 10.98,
  'air_quality': 2,
  'mestnost': 182.0,
  'salary': 84664.0,
  'infrastructure': 278},
 {'city': 'Электросталь',
  'lattitude': 55.7903785,
  'longitude': 38.4405711,
  'population': 158508,
  'temperature': 10.91,
  'air_quality': 2,
  'mestnost': 158.0,
  'salary': 88335.0,
  'infrastructure': 287},
 {'city': 'Истра',
  'lattitude': 55.9145993,
  'longitude': 36.8595482,
  'population': 42651,
  'temperature': 11.06,
  'air_quality': 2,
  'mestnost': 174.0,
  'salary': 135598.25,
  'infrastructure': 133},
 {'city': 'Ивантеевка',
  'lattitude': 55.9714098,
  'longitude': 37.9200739,
  'population': 79346,
  'temperature': 11.5,
  'air_quality': 2,
  'mestnost': 146.0,
  'salary': 91745.0,
  'infrastructure': 500},
 {'city': 'Электрогорск',
  'lattitude': 55.8792983,
  'longitude': 38.7858721,
  'population': 22950,
  'temperature': 10.7,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 55125.0,
  'infrastructure': 167},
 {'city': 'Солнечногорск',
  'lattitude': 56.1853501,
  'longitude': 36.9781536,
  'population': 51612,
  'temperature': 10.58,
  'air_quality': 2,
  'mestnost': 204.0,
  'salary': 82887.5,
  'infrastructure': 105},
 {'city': 'Озёры',
  'lattitude': 54.854209,
  'longitude': 38.5598853,
  'temperature': 8.87,
  'air_quality': 2,
  'mestnost': 121.0,
  'salary': 103875.0,
  'infrastructure': 23},
 {'city': 'Лапино',
  'lattitude': 56.2335594,
  'longitude': 42.2295566,
  'temperature': 5.68,
  'air_quality': 2,
  'mestnost': 132.0,
  'salary': 130289.47368421052,
  'infrastructure': 43},
 {'city': 'Реутов',
  'lattitude': 55.7622453,
  'longitude': 37.856555,
  'population': 106990,
  'temperature': 11.3,
  'air_quality': 2,
  'mestnost': 175.0,
  'salary': 109614.5,
  'infrastructure': 500},
 {'city': 'Орехово-Зуево',
  'lattitude': 55.8083278,
  'longitude': 38.9790038,
  'population': 118822,
  'temperature': 10.03,
  'air_quality': 2,
  'salary': 81039.3,
  'infrastructure': 153},
 {'city': 'Коломна',
  'lattitude': 55.0938743,
  'longitude': 38.7670121,
  'population': 144125,
  'temperature': 9.1,
  'air_quality': 2,
  'salary': 98147.5,
  'infrastructure': 178},
 {'city': 'Лыткарино',
  'lattitude': 55.5822477,
  'longitude': 37.9080217,
  'population': 58606,
  'temperature': 10.72,
  'air_quality': 2,
  'mestnost': 171.0,
  'salary': 92935.0,
  'infrastructure': 500},
 {'city': 'Чехов',
  'lattitude': 55.1426603,
  'longitude': 37.4545328,
  'population': 70548,
  'temperature': 10.37,
  'air_quality': 2,
  'mestnost': 156.0,
  'salary': 80542.5,
  'infrastructure': 114},
 {'city': 'Юдино',
  'lattitude': 54.475189,
  'longitude': 21.81341,
  'temperature': 11.88,
  'air_quality': 3,
  'mestnost': 54.0,
  'salary': 95689.47368421052,
  'infrastructure': 2},
 {'city': 'Новоивановское',
  'lattitude': 55.7050068,
  'longitude': 37.3661605,
  'temperature': 11.98,
  'air_quality': 2,
  'mestnost': 187.0,
  'salary': 116708.425,
  'infrastructure': 500},
 {'city': 'Алексино',
  'lattitude': 56.2340082,
  'longitude': 38.4989335,
  'temperature': 10.51,
  'air_quality': 2,
  'mestnost': 185.0,
  'salary': 95830.0,
  'infrastructure': 12},
 {'city': 'Фрязино',
  'lattitude': 55.954618,
  'longitude': 38.0567691,
  'population': 60437,
  'temperature': 11.29,
  'air_quality': 2,
  'mestnost': 166.0,
  'salary': 88237.5,
  'infrastructure': 443},
 {'city': 'Щербинка',
  'lattitude': 55.5069136,
  'longitude': 37.5673544,
  'temperature': 10.83,
  'air_quality': 2,
  'mestnost': 172.0,
  'salary': 103051.5,
  'infrastructure': 500},
 {'city': 'Жуковский',
  'lattitude': 55.5972801,
  'longitude': 38.1199863,
  'temperature': 10.84,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 109992.5,
  'infrastructure': 439},
 {'city': 'Ильинское-Усово',
  'lattitude': 55.767299,
  'longitude': 37.220472,
  'temperature': 11.34,
  'air_quality': 2,
  'mestnost': 168.0,
  'salary': 105960.9,
  'infrastructure': 500},
 {'city': 'Лешково',
  'lattitude': 48.9961281,
  'longitude': 29.876546,
  'temperature': 8.2,
  'air_quality': 3,
  'mestnost': 230.0,
  'salary': 106535.0,
  'infrastructure': 20},
 {'city': 'Дедовск',
  'lattitude': 55.8597808,
  'longitude': 37.1206449,
  'population': 29738,
  'temperature': 11.12,
  'air_quality': 2,
  'mestnost': 195.0,
  'salary': 94172.5,
  'infrastructure': 500},
 {'city': 'Луховицы',
  'lattitude': 54.9655573,
  'longitude': 39.0277188,
  'temperature': 8.3,
  'air_quality': 3,
  'mestnost': 137.0,
  'salary': 92655.95,
  'infrastructure': 38},
 {'city': 'Дзержинский',
  'lattitude': 55.6309186,
  'longitude': 37.8496653,
  'temperature': 11.12,
  'air_quality': 2,
  'mestnost': 161.0,
  'salary': 101960.0,
  'infrastructure': 500},
 {'city': 'Цибино',
  'lattitude': 55.4689419,
  'longitude': 38.4156043,
  'temperature': 10.47,
  'air_quality': 2,
  'mestnost': 120.0,
  'salary': 101921.03333333334,
  'infrastructure': 109},
 {'city': 'Марфино',
  'lattitude': 55.8309084,
  'longitude': 37.5914584,
  'temperature': 11.36,
  'air_quality': 2,
  'mestnost': 166.0,
  'salary': 104176.125,
  'infrastructure': 500},
 {'city': 'Гусь-Хрустальный',
  'lattitude': 55.6149968,
  'longitude': 40.6708665,
  'temperature': 5.61,
  'air_quality': 2,
  'mestnost': 132.0,
  'salary': 104652.95,
  'infrastructure': 55},
 {'city': 'Шемякино',
  'lattitude': 55.999135,
  'longitude': 37.368359,
  'temperature': 10.42,
  'air_quality': 2,
  'mestnost': 199.0,
  'salary': 116000.0,
  'infrastructure': 500},
 {'city': 'Шатура',
  'lattitude': 55.578403,
  'longitude': 39.5437584,
  'population': 33222,
  'temperature': 8.27,
  'air_quality': 2,
  'mestnost': 129.0,
  'salary': 105382.35294117648,
  'infrastructure': 34},
 {'city': 'Вешки',
  'lattitude': 56.4108561,
  'longitude': 38.7899205,
  'temperature': 10.19,
  'air_quality': 3,
  'mestnost': 200.0,
  'salary': 148675.0,
  'infrastructure': 70},
 {'city': 'Жаворонки',
  'lattitude': 45.0678088,
  'longitude': 33.7559827,
  'temperature': 11.4,
  'air_quality': 2,
  'mestnost': 36.0,
  'salary': 113152.5,
  'infrastructure': 73},
 {'city': 'Малоярославец',
  'lattitude': 55.012181,
  'longitude': 36.4590246,
  'population': 27791,
  'temperature': 8.81,
  'air_quality': 2,
  'mestnost': 198.0,
  'salary': 100434.375,
  'infrastructure': 88},
 {'city': 'Яхрома',
  'lattitude': 56.289936,
  'longitude': 37.4838441,
  'population': 14275,
  'temperature': 11.01,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 99903.5,
  'infrastructure': 110},
 {'city': 'Владивосток',
  'lattitude': 43.1150678,
  'longitude': 131.8855768,
  'temperature': 2.64,
  'air_quality': 3,
  'mestnost': 12.0,
  'salary': 138360.52631578947,
  'infrastructure': 500},
 {'city': 'Ржавки',
  'lattitude': 56.0129462,
  'longitude': 37.2243412,
  'temperature': 10.53,
  'air_quality': 2,
  'mestnost': 226.0,
  'salary': 104420.0,
  'infrastructure': 393},
 {'city': 'Лопатино',
  'lattitude': 52.545732,
  'longitude': 30.982559,
  'temperature': 10.07,
  'air_quality': 3,
  'mestnost': 141.0,
  'salary': 135362.5,
  'infrastructure': 216},
 {'city': 'Александров',
  'lattitude': 56.3962287,
  'longitude': 38.7111103,
  'temperature': 10.27,
  'air_quality': 2,
  'mestnost': 192.0,
  'salary': 110940.78571428571,
  'infrastructure': 68},
 {'city': 'Волоколамск',
  'lattitude': 56.0360129,
  'longitude': 35.9583358,
  'temperature': 8.96,
  'air_quality': 2,
  'mestnost': 175.0,
  'salary': 107600.0,
  'infrastructure': 47},
 {'city': 'Верхнее Мячково',
  'lattitude': 55.5503942,
  'longitude': 37.973121,
  'temperature': 10.92,
  'air_quality': 2,
  'mestnost': 135.0,
  'salary': 84666.66666666667,
  'infrastructure': 500},
 {'city': 'Северный',
  'lattitude': -38.00353045,
  'longitude': 175.95785260835657,
  'temperature': 14.43,
  'air_quality': 1,
  'mestnost': 372.0,
  'salary': 163317.15,
  'infrastructure': 2},
 {'city': 'Верея',
  'lattitude': 55.343238,
  'longitude': 36.185145,
  'temperature': 9.81,
  'air_quality': 2,
  'mestnost': 194.0,
  'salary': 111033.9,
  'infrastructure': 13},
 {'city': 'Руза',
  'lattitude': 55.6998907,
  'longitude': 36.1946992,
  'temperature': 9.89,
  'air_quality': 2,

In [ ]:
data

[{'city': 'Москва',
  'lattitude': 55.7504461,
  'longitude': 37.6174943,
  'population': 17125000,
  'temperature': 7.49,
  'air_quality': 2,
  'mestnost': 156.0,
  'salary': 362722.15,
  'infrastructure': 500},
 {'city': 'Немчиновка',
  'lattitude': 55.7208421,
  'longitude': 37.3666309,
  'temperature': 7.96,
  'air_quality': 2,
  'mestnost': 172.0,
  'salary': 135977.15,
  'infrastructure': 500},
 {'city': 'Химки',
  'lattitude': 55.8917293,
  'longitude': 37.4396994,
  'population': 244668,
  'temperature': 8.01,
  'air_quality': 2,
  'mestnost': 186.0,
  'salary': 107355.0,
  'infrastructure': 500},
 {'city': 'Балашиха',
  'lattitude': 55.8036225,
  'longitude': 37.9646488,
  'population': 450771,
  'temperature': 7.77,
  'air_quality': 2,
  'mestnost': 166.0,
  'salary': 104085.0,
  'infrastructure': 500},
 {'city': 'Пушкино',
  'lattitude': 59.722256,
  'longitude': 30.415731,
  'population': 105479,
  'temperature': 7.84,
  'air_quality': 2,
  'mestnost': 44.0,
  'salary': 99132.5,
  'infrastructure': 500},
 {'city': 'Красногорск',
  'lattitude': 55.8217545,
  'longitude': 37.3400897,
  'population': 171793,
  'temperature': 8.19,
  'air_quality': 2,
  'mestnost': 171.0,
  'salary': 98200.0,
  'infrastructure': 500},
 {'city': 'Люберцы',
  'lattitude': 55.6783142,
  'longitude': 37.89377,
  'population': 197705,
  'temperature': 7.82,
  'air_quality': 2,
  'mestnost': 141.0,
  'salary': 123000.0,
  'infrastructure': 500},
 {'city': 'Одинцово',
  'lattitude': 55.6711507,
  'longitude': 37.2727963,
  'population': 140537,
  'temperature': 8.04,
  'air_quality': 2,
  'mestnost': 188.0,
  'salary': 117355.0,
  'infrastructure': 500},
 {'city': 'Зеленоград',
  'lattitude': 55.9964233,
  'longitude': 37.198534,
  'population': 15493,
  'temperature': 7.74,
  'air_quality': 2,
  'mestnost': 233.0,
  'salary': 122400.0,
  'infrastructure': 397},
 {'city': 'Коммунарка',
  'lattitude': 54.382416,
  'longitude': 26.321512,
  'temperature': 7.14,
  'air_quality': 2,
  'mestnost': 248.0,
  'salary': 128941.17647058824,
  'infrastructure': 47},
 {'city': 'Дубна',
  'lattitude': 56.7362705,
  'longitude': 37.1623696,
  'population': 75144,
  'temperature': 6.63,
  'air_quality': 2,
  'mestnost': 118.0,
  'salary': 132975.8,
  'infrastructure': 65},
 {'city': 'Раменское',
  'lattitude': 55.5709361,
  'longitude': 38.2282099,
  'population': 116077,
  'temperature': 7.85,
  'air_quality': 2,
  'mestnost': 119.0,
  'salary': 88550.0,
  'infrastructure': 292},
 {'city': 'Обнинск',
  'lattitude': 55.0951738,
  'longitude': 36.611913,
  'population': 115029,
  'temperature': 2.25,
  'air_quality': 2,
  'mestnost': 174.0,
  'salary': 97960.52631578948,
  'infrastructure': 217},
 {'city': 'Звенигород',
  'lattitude': 55.7293613,
  'longitude': 36.8585382,
  'population': 22513,
  'temperature': 8.27,
  'air_quality': 2,
  'mestnost': 156.0,
  'salary': 100455.0,
  'infrastructure': 99},
 {'city': 'Нахабино',
  'lattitude': 55.8394789,
  'longitude': 37.1770987,
  'temperature': 8.03,
  'air_quality': 2,
  'mestnost': 183.0,
  'salary': 122150.0,
  'infrastructure': 500},
 {'city': 'Электроугли',
  'lattitude': 55.7184467,
  'longitude': 38.2228192,
  'population': 20823,
  'temperature': 7.75,
  'air_quality': 2,
  'mestnost': 151.0,
  'salary': 94107.5,
  'infrastructure': 337},
 {'city': 'Королёв',
  'lattitude': 55.9204898,
  'longitude': 37.8326289,
  'temperature': 7.75,
  'air_quality': 2,
  'mestnost': 167.0,
  'salary': 102766.66666666667,
  'infrastructure': 500},
 {'city': 'Тула',
  'lattitude': 45.2678347,
  'longitude': 1.7706797,
  'temperature': 17.02,
  'air_quality': 2,
  'mestnost': 226.0,
  'salary': 93740.0,
  'infrastructure': 44},
 {'city': 'Маково',
  'lattitude': 41.1187405,
  'longitude': 21.6103212,
  'temperature': 8.47,
  'air_quality': 3,
  'mestnost': 701.0,
  'salary': 84166.66666666667,
  'infrastructure': 2},
 {'city': 'Серпухов',
  'lattitude': 54.9155247,
  'longitude': 37.4195533,
  'population': 125817,
  'temperature': 6.35,
  'air_quality': 3,
  'mestnost': 156.0,
  'salary': 78735.0,
  'infrastructure': 148},
 {'city': 'Павловский Посад',
  'lattitude': 55.7813357,
  'longitude': 38.6507838,
  'temperature': 5.27,
  'air_quality': 2,
  'mestnost': 132.0,
  'salary': 88182.0,
  'infrastructure': 224},
 {'city': 'Гагарин',
  'lattitude': 55.553306,
  'longitude': 34.9968416,
  'population': 29041,
  'temperature': 6.21,
  'air_quality': 2,
  'mestnost': 192.0,
  'salary': 174638.88888888888,
  'infrastructure': 22},
 {'city': 'Всеволодово',
  'lattitude': 55.701454,
  'longitude': 38.4808664,
  'temperature': 7.75,
  'air_quality': 2,
  'mestnost': 154.0,
  'salary': 67500.0,
  'infrastructure': 178},
 {'city': 'Сергиев Посад',
  'lattitude': 56.3153529,
  'longitude': 38.1358208,
  'population': 104579,
  'temperature': 5.63,
  'air_quality': 2,
  'mestnost': 230.0,
  'salary': 95241.0,
  'infrastructure': 120},
 {'city': 'Михнево',
  'lattitude': 55.1212335,
  'longitude': 37.9584994,
  'temperature': 6.04,
  'air_quality': 2,
  'mestnost': 183.0,
  'salary': 126873.1,
  'infrastructure': 59},
 {'city': 'Владимир',
  'lattitude': 56.1288899,
  'longitude': 40.4075203,
  'population': 356168,
  'temperature': 3.36,
  'air_quality': 2,
  'mestnost': 152.0,
  'salary': 96657.8947368421,
  'infrastructure': 443},
 {'city': 'Тверь',
  'lattitude': 56.858675,
  'longitude': 35.9208284,
  'population': 419363,
  'temperature': 6.44,
  'air_quality': 2,
  'mestnost': 138.0,
  'salary': 82980.0,
  'infrastructure': 358},
 {'city': 'Ногинск',
  'lattitude': 55.8553511,
  'longitude': 38.4411898,
  'population': 229731,
  'temperature': 6.06,
  'air_quality': 2,
  'mestnost': 140.0,
  'salary': 118200.0,
  'infrastructure': 273},
 {'city': 'Домодедово',
  'lattitude': 55.4368213,
  'longitude': 37.7680693,
  'population': 127850,
  'temperature': 6.19,
  'air_quality': 2,
  'mestnost': 161.0,
  'salary': 107923.5,
  'infrastructure': 358},
 {'city': 'Подольск',
  'lattitude': 55.4308841,
  'longitude': 37.5453056,
  'population': 299660,
  'temperature': 7.34,
  'air_quality': 2,
  'mestnost': 157.0,
  'salary': 104037.5,
  'infrastructure': 437},
 {'city': 'Лунёво',
  'lattitude': 56.6144232,
  'longitude': 38.4956995,
  'temperature': 5.58,
  'air_quality': 3,
  'mestnost': 161.0,
  'salary': 68864.8,
  'infrastructure': 6},
 {'city': 'Рязань',
  'lattitude': 54.6295687,
  'longitude': 39.7425039,
  'population': 537622,
  'temperature': 2.9,
  'air_quality': 3,
  'mestnost': 118.0,
  'salary': 92262.5,
  'infrastructure': 341},
 {'city': 'Котельники',
  'lattitude': 55.661668,
  'longitude': 37.8673073,
  'population': 46763,
  'temperature': 7.75,
  'air_quality': 2,
  'mestnost': 149.0,
  'salary': 80530.0,
  'infrastructure': 500},
 {'city': 'Власиха',
  'lattitude': 53.2982076,
  'longitude': 83.5778361,
  'temperature': 5.44,
  'air_quality': 3,
  'mestnost': 181.0,
  'salary': 92532.725,
  'infrastructure': 500},
 {'city': 'Жуковка',
  'lattitude': 55.8681346,
  'longitude': 40.8400235,
  'temperature': 2.98,
  'air_quality': 2,
  'mestnost': 111.0,
  'salary': 155522.5,
  'infrastructure': 18},
 {'city': 'Егорьевск',
  'lattitude': 55.3829765,
  'longitude': 39.0356223,
  'population': 73766,
  'temperature': 3.83,
  'air_quality': 3,
  'mestnost': 148.0,
  'salary': 114770.025,
  'infrastructure': 82},
 {'city': 'Дубовая Роща',
  'lattitude': 54.4805301,
  'longitude': 22.4399827,
  'temperature': 7.58,
  'air_quality': 2,
  'mestnost': 108.0,
  'salary': 72484.375,
  'infrastructure': 2},
 {'city': 'Бронницы',
  'lattitude': 55.4219938,
  'longitude': 38.2590612,
  'population': 22567,
  'temperature': 7.84,
  'air_quality': 2,
  'mestnost': 137.0,
  'salary': 119089.47368421052,
  'infrastructure': 120},
 {'city': 'Кратово',
  'lattitude': 42.079261,
  'longitude': 22.1802182,
  'population': 6924,
  'temperature': 8.36,
  'air_quality': 3,
  'mestnost': 657.0,
  'salary': 99600.0,
  'infrastructure': 5},
 {'city': 'Заречье',
  'lattitude': 55.68776,
  'longitude': 37.3955454,
  'temperature': 8.14,
  'air_quality': 2,
  'salary': 109225.0,
  'infrastructure': 500},
 {'city': 'Щёлково',
  'lattitude': 55.9206499,
  'longitude': 37.9915576,
  'temperature': 7.86,
  'air_quality': 2,
  'mestnost': 147.0,
  'salary': 102375.0,
  'infrastructure': 500},
 {'city': 'Долгопрудный',
  'lattitude': 55.9341491,
  'longitude': 37.5142417,
  'population': 108861,
  'temperature': 7.96,
  'air_quality': 2,
  'mestnost': 194.0,
  'salary': 71764.0,
  'infrastructure': 500},
 {'city': 'Мытищи',
  'lattitude': 55.9094928,
  'longitude': 37.7339358,
  'population': 205397,
  'temperature': 7.79,
  'air_quality': 2,
  'mestnost': 158.0,
  'salary': 104650.0,
  'infrastructure': 500},
 {'city': 'Раздоры',
  'lattitude': 48.331689,
  'longitude': 35.7132916,
  'temperature': 10.02,
  'air_quality': 2,
  'mestnost': 90.0,
  'salary': 137300.0,
  'infrastructure': 1},
 {'city': 'Лобня',
  'lattitude': 56.0104473,
  'longitude': 37.4670831,
  'population': 88220,
  'temperature': 7.97,
  'air_quality': 2,
  'mestnost': 199.0,
  'salary': 108000.0,
  'infrastructure': 500},
 {'city': 'Видное',
  'lattitude': 55.5571496,
  'longitude': 37.7087142,
  'population': 66158,
  'temperature': 7.06,
  'air_quality': 2,
  'mestnost': 171.0,
  'salary': 96340.95,
  'infrastructure': 500},
 {'city': 'Путилково',
  'lattitude': 55.8625,
  'longitude': 37.390278,
  'temperature': 8.06,
  'air_quality': 2,
  'mestnost': 179.0,
  'salary': 137890.0,
  'infrastructure': 500},
 {'city': 'Калуга',
  'lattitude': 54.5101087,
  'longitude': 36.2598115,
  'population': 341892,
  'temperature': 6.02,
  'air_quality': 2,
  'mestnost': 201.0,
  'salary': 88095.0,
  'infrastructure': 433},
 {'city': 'Поярково',
  'lattitude': 56.0113486,
  'longitude': 37.3311934,
  'temperature': 7.94,
  'air_quality': 2,
  'mestnost': 197.0,
  'salary': 123431.25,
  'infrastructure': 500},
 {'city': 'Коробово',
  'lattitude': 55.8532508,
  'longitude': 40.2117645,
  'temperature': 3.21,
  'air_quality': 2,
  'mestnost': 151.0,
  'salary': 134741.72222222222,
  'infrastructure': 0},
 {'city': 'Наро-Фоминск',
  'lattitude': 55.3879473,
  'longitude': 36.7398309,
  'population': 62002,
  'temperature': 6.13,
  'air_quality': 2,
  'mestnost': 163.0,
  'salary': 99152.5,
  'infrastructure': 89},
 {'city': 'Онуфриево',
  'lattitude': 55.84697505,
  'longitude': 36.49969680889808,
  'temperature': 6.21,
  'air_quality': 2,
  'mestnost': 209.0,
  'salary': 85027.85714285714,
  'infrastructure': 19},
 {'city': 'Кубинка',
  'lattitude': 55.5755486,
  'longitude': 36.6952802,
  'population': 20157,
  'temperature': 6.69,
  'air_quality': 2,
  'mestnost': 210.0,
  'salary': 76012.0,
  'infrastructure': 74},
 {'city': 'Давыдово',
  'lattitude': 55.6078039,
  'longitude': 38.8585305,
  'temperature': 4.02,
  'air_quality': 2,
  'mestnost': 129.0,
  'salary': 99750.0,
  'infrastructure': 22},
 {'city': 'Юхнов',
  'lattitude': 54.7415766,
  'longitude': 35.2264393,
  'temperature': 6.66,
  'air_quality': 2,
  'mestnost': 159.0,
  'salary': 104012.5,
  'infrastructure': 14},
 {'city': 'Железнодорожный',
  'lattitude': 38.5507163,
  'longitude': 68.8305472,
  'temperature': 11.9,
  'air_quality': 2,
  'mestnost': 798.0,
  'salary': 104287.5,
  'infrastructure': 212},
 {'city': 'Новомосковск',
  'lattitude': 48.6358512,
  'longitude': 35.2595541,
  'population': 125647,
  'temperature': 10.2,
  'air_quality': 2,
  'mestnost': 57.0,
  'salary': 100442.1052631579,
  'infrastructure': 120},
 {'city': 'Апрелевка',
  'lattitude': 55.5454306,
  'longitude': 37.0730417,
  'temperature': 8.01,
  'air_quality': 2,
  'mestnost': 198.0,
  'salary': 85763.75,
  'infrastructure': 274},
 {'city': 'Голицыно',
  'lattitude': 55.6149602,
  'longitude': 36.9887625,
  'population': 17651,
  'temperature': 8.09,
  'air_quality': 2,
  'mestnost': 182.0,
  'salary': 85919.2,
  'infrastructure': 278},
 {'city': 'Электросталь',
  'lattitude': 55.7903785,
  'longitude': 38.4405711,
  'population': 158508,
  'temperature': 5.93,
  'air_quality': 2,
  'mestnost': 158.0,
  'salary': 91360.0,
  'infrastructure': 287},
 {'city': 'Истра',
  'lattitude': 55.9145993,
  'longitude': 36.8595482,
  'population': 42651,
  'temperature': 6.97,
  'air_quality': 2,
  'mestnost': 174.0,
  'salary': 136098.25,
  'infrastructure': 133},
 {'city': 'Ивантеевка',
  'lattitude': 55.9714098,
  'longitude': 37.9200739,
  'population': 79346,
  'temperature': 8.44,
  'air_quality': 2,
  'mestnost': 146.0,
  'salary': 94145.0,
  'infrastructure': 500},
 {'city': 'Электрогорск',
  'lattitude': 55.8792983,
  'longitude': 38.7858721,
  'population': 22950,
  'temperature': 4.66,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 57690.0,
  'infrastructure': 167},
 {'city': 'Солнечногорск',
  'lattitude': 56.1853501,
  'longitude': 36.9781536,
  'population': 51612,
  'temperature': 6.56,
  'air_quality': 2,
  'mestnost': 204.0,
  'salary': 88250.0,
  'infrastructure': 105},
 {'city': 'Озёры',
  'lattitude': 54.854209,
  'longitude': 38.5598853,
  'temperature': 5.66,
  'air_quality': 3,
  'mestnost': 121.0,
  'salary': 106441.17647058824,
  'infrastructure': 23},
 {'city': 'Лапино',
  'lattitude': 56.2335594,
  'longitude': 42.2295566,
  'temperature': 2.84,
  'air_quality': 2,
  'mestnost': 132.0,
  'salary': 140815.7894736842,
  'infrastructure': 43},
 {'city': 'Реутов',
  'lattitude': 55.7622453,
  'longitude': 37.856555,
  'population': 106990,
  'temperature': 8.26,
  'air_quality': 2,
  'mestnost': 175.0,
  'salary': 101789.5,
  'infrastructure': 500},
 {'city': 'Орехово-Зуево',
  'lattitude': 55.8083278,
  'longitude': 38.9790038,
  'population': 118822,
  'temperature': 3.36,
  'air_quality': 2,
  'mestnost': 122.0,
  'salary': 81039.3,
  'infrastructure': 153},
 {'city': 'Коломна',
  'lattitude': 55.0938743,
  'longitude': 38.7670121,
  'population': 144125,
  'temperature': 4.23,
  'air_quality': 3,
  'mestnost': 128.0,
  'salary': 94597.5,
  'infrastructure': 178},
 {'city': 'Лыткарино',
  'lattitude': 55.5822477,
  'longitude': 37.9080217,
  'population': 58606,
  'temperature': 7.17,
  'air_quality': 2,
  'mestnost': 171.0,
  'salary': 96185.0,
  'infrastructure': 500},
 {'city': 'Чехов',
  'lattitude': 55.1426603,
  'longitude': 37.4545328,
  'population': 70548,
  'temperature': 6.59,
  'air_quality': 2,
  'mestnost': 156.0,
  'salary': 76892.5,
  'infrastructure': 114},
 {'city': 'Юдино',
  'lattitude': 54.475189,
  'longitude': 21.81341,
  'temperature': 7.74,
  'air_quality': 2,
  'mestnost': 54.0,
  'salary': 95689.47368421052,
  'infrastructure': 2},
 {'city': 'Новоивановское',
  'lattitude': 55.7050068,
  'longitude': 37.3661605,
  'temperature': 7.84,
  'air_quality': 2,
  'mestnost': 187.0,
  'salary': 116999.775,
  'infrastructure': 500},
 {'city': 'Алексино',
  'lattitude': 56.2340082,
  'longitude': 38.4989335,
  'temperature': 5.88,
  'air_quality': 2,
  'mestnost': 185.0,
  'salary': 98505.0,
  'infrastructure': 12},
 {'city': 'Фрязино',
  'lattitude': 55.954618,
  'longitude': 38.0567691,
  'population': 60437,
  'temperature': 8.28,
  'air_quality': 2,
  'mestnost': 166.0,
  'salary': 83087.5,
  'infrastructure': 443},
 {'city': 'Щербинка',
  'lattitude': 55.5069136,
  'longitude': 37.5673544,
  'temperature': 7.3,
  'air_quality': 2,
  'mestnost': 172.0,
  'salary': 103051.5,
  'infrastructure': 500},
 {'city': 'Жуковский',
  'lattitude': 55.5972801,
  'longitude': 38.1199863,
  'temperature': 7.83,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 108242.5,
  'infrastructure': 439},
 {'city': 'Ильинское-Усово',
  'lattitude': 55.767299,
  'longitude': 37.220472,
  'temperature': 8.21,
  'air_quality': 2,
  'mestnost': 168.0,
  'salary': 101085.9,
  'infrastructure': 500},
 {'city': 'Лешково',
  'lattitude': 48.9961281,
  'longitude': 29.876546,
  'temperature': 6.98,
  'air_quality': 2,
  'mestnost': 230.0,
  'salary': 105735.0,
  'infrastructure': 20},
 {'city': 'Дедовск',
  'lattitude': 55.8597808,
  'longitude': 37.1206449,
  'population': 29738,
  'temperature': 7.95,
  'air_quality': 2,
  'mestnost': 195.0,
  'salary': 86512.5,
  'infrastructure': 500},
 {'city': 'Луховицы',
  'lattitude': 54.9655573,
  'longitude': 39.0277188,
  'temperature': 4.49,
  'air_quality': 3,
  'mestnost': 137.0,
  'salary': 100219.6,
  'infrastructure': 38},
 {'city': 'Дзержинский',
  'lattitude': 55.6309186,
  'longitude': 37.8496653,
  'temperature': 7.67,
  'air_quality': 2,
  'mestnost': 161.0,
  'salary': 102285.0,
  'infrastructure': 500},
 {'city': 'Цибино',
  'lattitude': 55.4689419,
  'longitude': 38.4156043,
  'temperature': 7.94,
  'air_quality': 2,
  'mestnost': 120.0,
  'salary': 104915.39285714286,
  'infrastructure': 109},
 {'city': 'Марфино',
  'lattitude': 55.8309084,
  'longitude': 37.5914584,
  'temperature': 8.16,
  'air_quality': 2,
  'mestnost': 166.0,
  'salary': 103139.775,
  'infrastructure': 500},
 {'city': 'Гусь-Хрустальный',
  'lattitude': 55.6149968,
  'longitude': 40.6708665,
  'temperature': 2.54,
  'air_quality': 2,
  'mestnost': 132.0,
  'salary': 110427.95,
  'infrastructure': 55},
 {'city': 'Шемякино',
  'lattitude': 55.999135,
  'longitude': 37.368359,
  'temperature': 7.94,
  'air_quality': 2,
  'mestnost': 199.0,
  'salary': 116000.0,
  'infrastructure': 500},
 {'city': 'Шатура',
  'lattitude': 55.578403,
  'longitude': 39.5437584,
  'population': 33222,
  'temperature': 4.11,
  'air_quality': 3,
  'mestnost': 129.0,
  'salary': 110088.23529411765,
  'infrastructure': 34},
 {'city': 'Вешки',
  'lattitude': 56.4108561,
  'longitude': 38.7899205,
  'temperature': 5.89,
  'air_quality': 3,
  'mestnost': 200.0,
  'salary': 144675.0,
  'infrastructure': 70},
 {'city': 'Жаворонки',
  'lattitude': 45.0678088,
  'longitude': 33.7559827,
  'temperature': 10.78,
  'air_quality': 2,
  'mestnost': 36.0,
  'salary': 113152.5,
  'infrastructure': 73},
 {'city': 'Малоярославец',
  'lattitude': 55.012181,
  'longitude': 36.4590246,
  'population': 27791,
  'temperature': 2.13,
  'air_quality': 2,
  'mestnost': 198.0,
  'salary': 102884.375,
  'infrastructure': 88},
 {'city': 'Яхрома',
  'lattitude': 56.289936,
  'longitude': 37.4838441,
  'population': 14275,
  'temperature': 6.48,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 106090.0,
  'infrastructure': 110},
 {'city': 'Владивосток',
  'lattitude': 43.1150678,
  'longitude': 131.8855768,
  'population': 606589,
  'temperature': 0.45,
  'air_quality': 3,
  'mestnost': 12.0,
  'salary': 164657.8947368421,
  'infrastructure': 500},
 {'city': 'Ржавки',
  'lattitude': 56.0129462,
  'longitude': 37.2243412,
  'temperature': 7.77,
  'air_quality': 2,
  'mestnost': 226.0,
  'salary': 104420.0,
  'infrastructure': 393},
 {'city': 'Лопатино',
  'lattitude': 52.545732,
  'longitude': 30.982559,
  'temperature': 12.01,
  'air_quality': 3,
  'mestnost': 141.0,
  'salary': 128794.11764705883,
  'infrastructure': 216},
 {'city': 'Александров',
  'lattitude': 56.3962287,
  'longitude': 38.7111103,
  'temperature': 5.9,
  'air_quality': 2,
  'mestnost': 192.0,
  'salary': 105687.5,
  'infrastructure': 68},
 {'city': 'Волоколамск',
  'lattitude': 56.0360129,
  'longitude': 35.9583358,
  'population': 19824,
  'temperature': 5.29,
  'air_quality': 2,
  'mestnost': 175.0,
  'salary': 107425.0,
  'infrastructure': 47},
 {'city': 'Верхнее Мячково',
  'lattitude': 55.5503942,
  'longitude': 37.973121,
  'temperature': 6.95,
  'air_quality': 2,
  'mestnost': 135.0,
  'salary': 84666.66666666667,
  'infrastructure': 500},
 {'city': 'Северный',
  'lattitude': -38.00353045,
  'longitude': 175.95785260835657,
  'temperature': 13.53,
  'air_quality': 1,
  'mestnost': 372.0,
  'salary': 164567.15,
  'infrastructure': 2},
 {'city': 'Верея',
  'lattitude': 55.343238,
  'longitude': 36.185145,
  'population': 5123,
  'temperature': 6.56,
  'air_quality': 2,
  'mestnost': 194.0,
  'salary': 108283.9,
  'infrastructure': 13},
 {'city': 'Руза',

In [ ]:
new = pd.DataFrame(data)
new

,city,lattitude,longitude,population,temperature,air_quality,mestnost,salary,infrastructure
0,Москва,55.750446,37.617494,17125000.0,11.72,2,156.0,375012.50,500
1,Немчиновка,55.720842,37.366631,NaN,11.90,2,172.0,141977.15,500
2,Химки,55.891729,37.439699,244668.0,10.94,2,186.0,104605.00,500
3,Балашиха,55.803623,37.964649,450771.0,11.26,2,166.0,107832.50,500
4,Пушкино,59.722256,30.415731,105479.0,10.53,2,44.0,97655.00,500
...,...,...,...,...,...,...,...,...,...
534,Ужесельга,61.723103,34.482700,NaN,6.87,2,93.0,NaN,174
535,Соловьи,57.685852,28.325863,NaN,11.06,2,44.0,107656.25,116
536,Рауталахти,61.623407,29.600232,NaN,8.30,2,113.0,57500.00,6
537,Бесовец,61.865685,34.158962,NaN,7.67,2,42.0,NaN,156
538,Ладва-Ветка,61.362133,34.446932,NaN,5.35,2,105.0,NaN,0

In [ ]:
new.to_csv('api_with_logs.csv')

In [ ]:
pd.DataFrame(data).to_csv('data1.csv')

In [ ]:
ORYOL_ind = list(cities).index('Орёл')
cities2 = cities[ORYOL_ind:]
cities2

array(['Орёл', 'Козельск', 'Касимов', 'Некрасовское', 'Вязьма', 'Мышкин',
       'Людиново', 'Киреевск', 'Сафоново', 'Красное-на-Волге', 'Белый',
       'Бологое', 'Навашино', 'Киров', 'Лев Толстой', 'Сасово',
       'Архиповка', 'Шайковка', 'Шуя', 'Ивановская область', 'Осташков',
       'Меленки', 'Вязники', 'Волгореченск', 'Сухиничи', 'Лежнево',
       'Бежецк', 'Петрово', 'Кувшиново', 'Ново-Талицы', 'Скопин',
       'Фанерник', 'Пришня', 'Угра', 'Ельня', 'Старожилово', 'Зарубино',
       'Пителино', 'Милославское', 'Комсомольск', 'Южа', 'Одоев',
       'Ленинский район', 'Мошок', 'Патакино', 'Мелехово', 'Палех',
       'Бегоулево', 'Судогда', 'Чаплыгин', 'Пожилино', 'Товарковский',
       'Новомичуринск', 'Спасск-Рязанский', 'Новосибирск', 'Самара',
       'Томск', 'Заковряжино', 'Воеводское', 'Камень-на-Оби', 'Барнаул',
       'Бердск', 'Каргасок', 'Горный', 'Кемерово', 'Новокузнецк',
       'Ачинск', 'Барышево', 'Краснобродский', 'Центральный', 'Мыски',
       'Киселёвск', 'Юрга', 'Купино', 'Тальменка', 'Парабель', 'Татарск',
       'Ленинск-Кузнецкий', 'Республика Алтай', 'Тогучин',
       'Анжеро-Судженск', 'Междуреченск', 'Барабинск',
       'Новосибирский район', 'Северск', 'Белово', 'Томская область',
       'Прокопьевск', 'Яшкино', 'Бийск', 'Рубцовск', 'Полысаево',
       'Ордынское', 'Горно-Алтайск', 'Двуречье', 'Алтайское', 'Карасук',
       'Колпашево', 'Озерки', 'Златоуст', 'Новоалтайск', 'Южный',
       'Зоркальцево', 'Топки', 'Алтайский край', 'Кемеровский район',
       'Жемчужный', 'Искитим', 'Смоленское', 'Назарово', 'Павловск',
       'Тяжинский', 'Яровое', 'Новолуговое', 'Веселовское', 'Маслянино',
       'Дубинино', 'Советский район', 'Абаза', 'Салаир', 'Шарыпово',
       'Сибирский', 'Боготол', 'Краснозёрское', 'Старобелокуриха',
       'Белокуриха', 'Акимовка', 'Краснообск', 'Ордынский район',
       'Алейск', 'Шира', 'Славгород', 'Кольцово', 'Благовещенка', 'Чемал',
       'Таштагол', 'Кривошеино', 'Асино', 'Ужур', 'Налобиха', 'Ишим',
       'Мошково', 'Сростки', 'Черепаново', 'Кисловка', 'Завьялово',
       'Павлодар', 'Кулунда', 'Гурьевск', 'Волчиха', 'Крапивинский',
       'Майма', 'Линёво', 'Болотное', 'Куйбышев', 'Чарышское', 'Убинское',
       'Зональная станция', 'Прокудское', 'Заринск', 'Криводановка',
       'Баган', 'Копьёво', 'Осинники', 'Мельниково', 'Мироновка',
       'Дорогино', 'Верх-Чуманка', 'Среднесибирский', 'Чаны', 'Сорск',
       'Утянка', 'Толмачёво', 'Романово', 'Крутиха', 'Аскиз', 'Тисуль',
       'Каменка', 'Новосафоновский', 'Кызыл-Озёк', 'Яркуль',
       'Бельтирское', 'Кыштовка', 'Довольное', 'Медведское', 'Обь',
       'Онгудай', 'Абакан', 'Элитный', 'Троицкое',
       'Городской округ Барнаул', 'Зудилово', 'Загорский',
       'Искитимский район', 'Шебалино', 'Алтайский район', 'Чистоозерное',
       'Александровское', 'Каховка', 'Поспелиха', 'Верх-Кучук',
       'Станция Мочище', 'Мошковский район', 'Усть-Кан', 'Ларичиха',
       'Глядень', 'Кирзинское', 'Октябрьский', 'Ужурский район',
       'Коченёво', 'Вершинино', 'Михайловское', 'Зеленогорский',
       'Черногорск', 'Калачинск', 'Минусинск', 'Черлак', 'Курчатов',
       'Саяногорск', 'Кормиловка', 'Козулька', 'Макеевка', 'Шушенское',
       'Белый Яр', 'Усть-Кокса', 'Морозовка', 'Мульта', 'Ростовка',
       'Большие Сыры', 'Красноярск', 'Большеречье', 'Тара',
       'Усть-Коксинский район', 'Русская Поляна', 'Усть-Абакан', 'Иня',
       'Балахта', 'Усть-Каменогорск', 'Улаган', 'Черёмушки', 'Расцвет',
       'Идринское', 'Семей', 'Курай', 'Таврическое', 'Знаменское',
       'Новочернореченский', 'Харламово', 'Воскресенка', 'Солнечное',
       'Анаш', 'Усть-Заостровка', 'Тесь', 'Оконешниково', 'Ачаирский',
       'Омск', 'Краснотуранск', 'Боград', 'Новомосковка', 'Бея',
       'Павлодарская область', 'Новосёлово', 'Междуречье',
       'Большой Атмас', 'Первомайское', 'Зеленый Бор', 'Павлоградка',
       'Катанда', 'Орлово', 'Омский', 'Богословка', 'Новокурск',
       'Лугавское', 'Большегривское', 'Сыропятское', 'Калинино',
       'Пировское', 'Прииртышье', 'Новороссийка', 'Шунеры', 'Кызыл',
       'Нововаршавка', 'Андреевка', 'Санкт-Петербург', 'Красное Село',
       'Сестрорецк', 'Ропша', 'Репино', 'Рощино', 'Сосновый Бор',
       'Всеволожск', 'Выборг', 'Ягодное', 'Пушкин', 'Гдов',
       'Новосаратовка', 'Шушары', 'Московский район', 'Кингисепп',
       'Энколово', 'Янино-1', 'Ульяновка', 'Стрельна', 'Мурино',
       'Сосново', 'Великий Новгород', 'Луга', 'Порошкино', 'Агалатово',
       'Сортавала', 'Разметелево', 'Гатчина', 'Колпино', 'Кириши',
       'Сланцы', 'Сертолово', 'Тихвин', 'Ковалёво', 'Петергоф',
       'Синявино', 'Волхов', 'Вырица', 'Кудрово', 'Парголово',
       'Кронштадт', 'Щеглово', 'Посёлок имени Свердлова', 'Бугры',
       'Бокситогорск', 'Приладожский', 'Ленинское', 'Чудово',
       'Посёлок имени Морозова', 'Виллозское городское поселение',
       'Тосно', 'Новолисино', 'Новогорелово', 'Новоселицы', 'Питкяранта',
       'Невский округ', 'Ильинский', 'Песочный', 'Лесколово', 'Сясьстрой',
       'Никольское', 'Сапёрный', 'Советский', 'Коммунар', 'Лодейное Поле',
       'Шлиссельбург', 'Малое Карлино', 'Старая', 'Ленсоветовский',
       'Воейково', 'Плюсса', 'Петрозаводск', 'Псков', 'Боровичи',
       'Валдай', 'Пикалево', 'Едрово', 'Чагода', 'Дедовичи', 'Вилга',
       'Вяртсиля', 'Ляскеля', 'Подпорожье', 'Новая Вилга', 'Озёрный',
       'Старая Русса', 'Псковский район', 'Окуловка', 'Печоры', 'Остров',
       'Орел', 'Яжелбицы', 'Выползово', 'Демянск', 'Писковичи', 'Сольцы',
       'Федоровщина', 'Парфино', 'Изборск', 'Городище', 'Порхов',
       'Череха', 'Ваулино', 'Пряжа', 'Любытино', 'Неелово 2-е', 'Дно',
       'Ужесельга', 'Соловьи', 'Рауталахти', 'Бесовец', 'Ладва-Ветка'],
      dtype=object)

In [ ]:
ninja_API = 'Uwi1SFJtGr0E7jkUsjiXwNW60cdQxcYKTx1wr0vH'
geo_API = '066646a31ef941b4703ae590b879a061'
density_API = 'c7cbb8c5f78c44f1b6813438181dfce3'
data2 = []
for city in cities2:
  print(f'we are looking for {city}')
  vowel = {'city':city}
  req_geo = requests.get(f'http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=1&appid={geo_API}', headers={'X-API-KEY':geo_API})
  req_geo.json()
  if len (req_geo.json()) == 0:
    print(f'there is no such city found {city}')
    continue
  geo = req_geo.json()[0]
  lattitude = geo['lat']
  longitude = geo['lon']
  vowel['lattitude'] = lattitude
  vowel['longitude'] = longitude
  eng_name = geo['name']
  if 'local_names' in geo and 'en' in geo['local_names']:
    eng_name = geo['local_names']['en']
  req_city = requests.get(f'https://api.api-ninjas.com/v1/city?name={eng_name}', headers={'X-Api-Key': ninja_API})
  req_city.json()
  if type(req_city.json()) == list and len(req_city.json()) > 0:
    if 'population' in req_city.json()[0]:
      vowel['population'] = req_city.json()[0]['population']
  req_wheather = requests.get(f'https://api.openweathermap.org/data/2.5/weather?lat={lattitude}&lon={longitude}&units=metric&appid={geo_API}', headers={'X-Api-Key':geo_API})
  req_wheather.json()
  vowel['temperature'] = req_wheather.json()['main']['temp']
  req_air = requests.get(f'http://api.openweathermap.org/data/2.5/air_pollution?lat={lattitude}&lon={longitude}&appid={geo_API}', headers={'X-API-KEY':geo_API})
  req_air.json()
  vowel['air_quality'] = req_air.json()['list'][0]['main']['aqi']
  try:
    req_mestnost = requests.get(f'https://api.open-meteo.com/v1/elevation?latitude={lattitude}&longitude={longitude}')
    req_mestnost.json()
    if 'elevation' in req_mestnost.json():
      vowel['mestnost'] = req_mestnost.json()['elevation'][0]
  except:
    print('raj_kumar_gay')
  req_salary = requests.get(f'https://api.hh.ru/vacancies?text={city}&only_with_salary=true&per_page=20')
  req_salary.json()
  salary = []
  for elem in req_salary.json()['items']:
    wage = elem['salary']
    if wage != None and wage['currency'] == 'RUR':
      if wage['to'] and wage['from']:
        salary.append((wage['to'] + wage['from']) / 2)
      elif wage['to']:
        salary.append(wage['to'])
      elif wage['from']:
        salary.append(wage['from'])
  if len(salary) != 0:
    vowel['salary'] = sum(salary) / len(salary)
  req_infrastructure = requests.get(f'https://api.geoapify.com/v2/places?categories=commercial.vehicle,service.vehicle&filter=circle:{longitude},{lattitude},15000&limit=500&apiKey={density_API}', headers={'X-API-KEY':density_API})
  req_infrastructure.json()
  vowel['infrastructure'] = len(req_infrastructure.json()['features'])
  data2.append(vowel)
  time.sleep(0.5)
data2

we are looking for Орёл
we are looking for Козельск
we are looking for Касимов
we are looking for Некрасовское
we are looking for Вязьма
we are looking for Мышкин
we are looking for Людиново
we are looking for Киреевск
we are looking for Сафоново
we are looking for Красное-на-Волге
we are looking for Белый
we are looking for Бологое
we are looking for Навашино
we are looking for Киров
we are looking for Лев Толстой
we are looking for Сасово
we are looking for Архиповка
we are looking for Шайковка
we are looking for Шуя
we are looking for Ивановская область
there is no such city found Ивановская область
we are looking for Осташков
we are looking for Меленки
we are looking for Вязники
we are looking for Волгореченск
we are looking for Сухиничи
we are looking for Лежнево
we are looking for Бежецк
we are looking for Петрово
we are looking for Кувшиново
we are looking for Ново-Талицы
we are looking for Скопин
raj_kumar_gay
we are looking for Фанерник
raj_kumar_gay
we are looking for Пришня
we are looking for Угра
we are looking for Ельня
we are looking for Старожилово
we are looking for Зарубино
we are looking for Пителино
we are looking for Милославское
we are looking for Комсомольск
we are looking for Южа
we are looking for Одоев
we are looking for Ленинский район
we are looking for Мошок
we are looking for Патакино
raj_kumar_gay
we are looking for Мелехово
we are looking for Палех
we are looking for Бегоулево
we are looking for Судогда
we are looking for Чаплыгин
we are looking for Пожилино
we are looking for Товарковский
we are looking for Новомичуринск
we are looking for Спасск-Рязанский
we are looking for Новосибирск
we are looking for Самара
we are looking for Томск
we are looking for Заковряжино
we are looking for Воеводское
we are looking for Камень-на-Оби
we are looking for Барнаул
we are looking for Бердск
we are looking for Каргасок
we are looking for Горный
we are looking for Кемерово
we are looking for Новокузнецк
we are looking for Ачинск
we are looking for Барышево
we are looking for Краснобродский
raj_kumar_gay
we are looking for Центральный
we are looking for Мыски
we are looking for Киселёвск
we are looking for Юрга
we are looking for Купино
we are looking for Тальменка
we are looking for Парабель
we are looking for Татарск
we are looking for Ленинск-Кузнецкий
we are looking for Республика Алтай
there is no such city found Республика Алтай
we are looking for Тогучин
we are looking for Анжеро-Судженск
we are looking for Междуреченск
we are looking for Барабинск
we are looking for Новосибирский район
there is no such city found Новосибирский район
we are looking for Северск
we are looking for Белово
we are looking for Томская область
there is no such city found Томская область
we are looking for Прокопьевск
we are looking for Яшкино
we are looking for Бийск
we are looking for Рубцовск
we are looking for Полысаево
we are looking for Ордынское
we are looking for Горно-Алтайск
we are looking for Двуречье
we are looking for Алтайское
we are looking for Карасук
we are looking for Колпашево
we are looking for Озерки
we are looking for Златоуст
we are looking for Новоалтайск
we are looking for Южный
we are looking for Зоркальцево
we are looking for Топки
we are looking for Алтайский край
there is no such city found Алтайский край
we are looking for Кемеровский район
there is no such city found Кемеровский район
we are looking for Жемчужный
we are looking for Искитим
we are looking for Смоленское
we are looking for Назарово
we are looking for Павловск
we are looking for Тяжинский
we are looking for Яровое
we are looking for Новолуговое
we are looking for Веселовское
we are looking for Маслянино
we are looking for Дубинино
we are looking for Советский район
we are looking for Абаза
we are looking for Салаир
we are looking for Шарыпово
we are looking for Сибирский
we are looking for Боготол
we are looking for Краснозёрское
we are looking for Старобелокуриха
we are looking for Белокуриха
we are looking for Акимовка
we are looking for Краснообск
we are looking for Ордынский район
there is no such city found Ордынский район
we are looking for Алейск
we are looking for Шира
we are looking for Славгород
we are looking for Кольцово
we are looking for Благовещенка
we are looking for Чемал
we are looking for Таштагол
we are looking for Кривошеино
we are looking for Асино
we are looking for Ужур
we are looking for Налобиха
we are looking for Ишим
we are looking for Мошково
we are looking for Сростки
we are looking for Черепаново
we are looking for Кисловка
we are looking for Завьялово
we are looking for Павлодар
we are looking for Кулунда
we are looking for Гурьевск
we are looking for Волчиха
we are looking for Крапивинский
we are looking for Майма
we are looking for Линёво
we are looking for Болотное
we are looking for Куйбышев
we are looking for Чарышское
we are looking for Убинское
we are looking for Зональная станция
we are looking for Прокудское
we are looking for Заринск
we are looking for Криводановка
we are looking for Баган
we are looking for Копьёво
we are looking for Осинники
we are looking for Мельниково
we are looking for Мироновка
we are looking for Дорогино
we are looking for Верх-Чуманка
we are looking for Среднесибирский
we are looking for Чаны
we are looking for Сорск
we are looking for Утянка
we are looking for Толмачёво
we are looking for Романово
we are looking for Крутиха
we are looking for Аскиз
we are looking for Тисуль
we are looking for Каменка
we are looking for Новосафоновский
we are looking for Кызыл-Озёк
we are looking for Яркуль
we are looking for Бельтирское
we are looking for Кыштовка
we are looking for Довольное
we are looking for Медведское
we are looking for Обь
we are looking for Онгудай
we are looking for Абакан
we are looking for Элитный
we are looking for Троицкое
we are looking for Городской округ Барнаул
there is no such city found Городской округ Барнаул
we are looking for Зудилово
we are looking for Загорский
we are looking for Искитимский район
there is no such city found Искитимский район
we are looking for Шебалино
we are looking for Алтайский район
there is no such city found Алтайский район
we are looking for Чистоозерное
we are looking for Александровское
we are looking for Каховка
raj_kumar_gay
we are looking for Поспелиха
we are looking for Верх-Кучук
we are looking for Станция Мочище
there is no such city found Станция Мочище
we are looking for Мошковский район
we are looking for Усть-Кан
we are looking for Ларичиха
we are looking for Глядень
we are looking for Кирзинское
we are looking for Октябрьский
we are looking for Ужурский район
we are looking for Коченёво
we are looking for Вершинино
we are looking for Михайловское
we are looking for Зеленогорский
we are looking for Черногорск
raj_kumar_gay
we are looking for Калачинск
we are looking for Минусинск
we are looking for Черлак
we are looking for Курчатов
we are looking for Саяногорск
we are looking for Кормиловка
we are looking for Козулька
we are looking for Макеевка
we are looking for Шушенское
we are looking for Белый Яр
we are looking for Усть-Кокса
we are looking for Морозовка
we are looking for Мульта
we are looking for Ростовка
we are looking for Большие Сыры
we are looking for Красноярск
we are looking for Большеречье
we are looking for Тара
we are looking for Усть-Коксинский район
there is no such city found Усть-Коксинский район
we are looking for Русская Поляна
we are looking for Усть-Абакан
we are looking for Иня
we are looking for Балахта
we are looking for Усть-Каменогорск
we are looking for Улаган
we are looking for Черёмушки
we are looking for Расцвет
we are looking for Идринское
we are looking for Семей
we are looking for Курай
we are looking for Таврическое
we are looking for Знаменское
we are looking for Новочернореченский
we are looking for Харламово
we are looking for Воскресенка
we are looking for Солнечное
we are looking for Анаш
we are looking for Усть-Заостровка
we are looking for Тесь
we are looking for Оконешниково
we are looking for Ачаирский
we are looking for Омск
we are looking for Краснотуранск
we are looking for Боград
we are looking for Новомосковка
we are looking for Бея
we are looking for Павлодарская область
there is no such city found Павлодарская область
we are looking for Новосёлово
we are looking for Междуречье
we are looking for Большой Атмас
raj_kumar_gay
we are looking for Первомайское
raj_kumar_gay
we are looking for Зеленый Бор
we are looking for Павлоградка
we are looking for Катанда
we are looking for Орлово
we are looking for Омский
we are looking for Богословка
we are looking for Новокурск
we are looking for Лугавское
we are looking for Большегривское
we are looking for Сыропятское
we are looking for Калинино
we are looking for Пировское
we are looking for Прииртышье
we are looking for Новороссийка
we are looking for Шунеры
we are looking for Кызыл
we are looking for Нововаршавка
we are looking for Андреевка
we are looking for Санкт-Петербург
we are looking for Красное Село
we are looking for Сестрорецк
we are looking for Ропша
we are looking for Репино
we are looking for Рощино
we are looking for Сосновый Бор
we are looking for Всеволожск
we are looking for Выборг
we are looking for Ягодное
we are looking for Пушкин
we are looking for Гдов
we are looking for Новосаратовка
we are looking for Шушары
we are looking for Московский район
we are looking for Кингисепп
we are looking for Энколово
we are looking for Янино-1
we are looking for Ульяновка
we are looking for Стрельна
we are looking for Мурино
we are looking for Сосново
we are looking for Великий Новгород
we are looking for Луга
we are looking for Порошкино
we are looking for Агалатово
we are looking for Сортавала
we are looking for Разметелево
we are looking for Гатчина
we are looking for Колпино
we are looking for Кириши
we are looking for Сланцы
we are looking for Сертолово
we are looking for Тихвин
we are looking for Ковалёво

KeyboardInterrupt:

In [ ]:
pd.DataFrame(data2).to_csv('data2.csv')

In [ ]:
koval_ind = list(cities).index('Ковалёво')
cities3 = cities[koval_ind:]
cities3

array(['Ковалёво', 'Петергоф', 'Синявино', 'Волхов', 'Вырица', 'Кудрово',
       'Парголово', 'Кронштадт', 'Щеглово', 'Посёлок имени Свердлова',
       'Бугры', 'Бокситогорск', 'Приладожский', 'Ленинское', 'Чудово',
       'Посёлок имени Морозова', 'Виллозское городское поселение',
       'Тосно', 'Новолисино', 'Новогорелово', 'Новоселицы', 'Питкяранта',
       'Невский округ', 'Ильинский', 'Песочный', 'Лесколово', 'Сясьстрой',
       'Никольское', 'Сапёрный', 'Советский', 'Коммунар', 'Лодейное Поле',
       'Шлиссельбург', 'Малое Карлино', 'Старая', 'Ленсоветовский',
       'Воейково', 'Плюсса', 'Петрозаводск', 'Псков', 'Боровичи',
       'Валдай', 'Пикалево', 'Едрово', 'Чагода', 'Дедовичи', 'Вилга',
       'Вяртсиля', 'Ляскеля', 'Подпорожье', 'Новая Вилга', 'Озёрный',
       'Старая Русса', 'Псковский район', 'Окуловка', 'Печоры', 'Остров',
       'Орел', 'Яжелбицы', 'Выползово', 'Демянск', 'Писковичи', 'Сольцы',
       'Федоровщина', 'Парфино', 'Изборск', 'Городище', 'Порхов',
       'Череха', 'Ваулино', 'Пряжа', 'Любытино', 'Неелово 2-е', 'Дно',
       'Ужесельга', 'Соловьи', 'Рауталахти', 'Бесовец', 'Ладва-Ветка'],
      dtype=object)

In [ ]:
ninja_API = 'Uwi1SFJtGr0E7jkUsjiXwNW60cdQxcYKTx1wr0vH'
geo_API = '066646a31ef941b4703ae590b879a061'
density_API = 'c7cbb8c5f78c44f1b6813438181dfce3'
data3 = []
for city in cities3:
  print(f'we are looking for {city}')
  vowel = {'city':city}
  req_geo = requests.get(f'http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=1&appid={geo_API}', headers={'X-API-KEY':geo_API})
  req_geo.json()
  if len (req_geo.json()) == 0:
    print(f'there is no such city found {city}')
    continue
  geo = req_geo.json()[0]
  lattitude = geo['lat']
  longitude = geo['lon']
  vowel['lattitude'] = lattitude
  vowel['longitude'] = longitude
  eng_name = geo['name']
  if 'local_names' in geo and 'en' in geo['local_names']:
    eng_name = geo['local_names']['en']
  req_city = requests.get(f'https://api.api-ninjas.com/v1/city?name={eng_name}', headers={'X-Api-Key': ninja_API})
  req_city.json()
  if type(req_city.json()) == list and len(req_city.json()) > 0:
    if 'population' in req_city.json()[0]:
      vowel['population'] = req_city.json()[0]['population']
  req_wheather = requests.get(f'https://api.openweathermap.org/data/2.5/weather?lat={lattitude}&lon={longitude}&units=metric&appid={geo_API}', headers={'X-Api-Key':geo_API})
  req_wheather.json()
  vowel['temperature'] = req_wheather.json()['main']['temp']
  req_air = requests.get(f'http://api.openweathermap.org/data/2.5/air_pollution?lat={lattitude}&lon={longitude}&appid={geo_API}', headers={'X-API-KEY':geo_API})
  req_air.json()
  vowel['air_quality'] = req_air.json()['list'][0]['main']['aqi']
  try:
    req_mestnost = requests.get(f'https://api.open-meteo.com/v1/elevation?latitude={lattitude}&longitude={longitude}')
    req_mestnost.json()
    if 'elevation' in req_mestnost.json():
      vowel['mestnost'] = req_mestnost.json()['elevation'][0]
  except:
    print('raj_kumar_gay')
  req_salary = requests.get(f'https://api.hh.ru/vacancies?text={city}&only_with_salary=true&per_page=20')
  req_salary.json()
  salary = []
  for elem in req_salary.json()['items']:
    wage = elem['salary']
    if wage != None and wage['currency'] == 'RUR':
      if wage['to'] and wage['from']:
        salary.append((wage['to'] + wage['from']) / 2)
      elif wage['to']:
        salary.append(wage['to'])
      elif wage['from']:
        salary.append(wage['from'])
  if len(salary) != 0:
    vowel['salary'] = sum(salary) / len(salary)
  req_infrastructure = requests.get(f'https://api.geoapify.com/v2/places?categories=commercial.vehicle,service.vehicle&filter=circle:{longitude},{lattitude},15000&limit=500&apiKey={density_API}', headers={'X-API-KEY':density_API})
  req_infrastructure.json()
  vowel['infrastructure'] = len(req_infrastructure.json()['features'])
  data3.append(vowel)
  time.sleep(0.5)
data3

we are looking for Ковалёво
we are looking for Петергоф
we are looking for Синявино
we are looking for Волхов
we are looking for Вырица
we are looking for Кудрово
we are looking for Парголово
we are looking for Кронштадт
we are looking for Щеглово
we are looking for Посёлок имени Свердлова
we are looking for Бугры
we are looking for Бокситогорск
we are looking for Приладожский
we are looking for Ленинское
we are looking for Чудово
we are looking for Посёлок имени Морозова
we are looking for Виллозское городское поселение
we are looking for Тосно
we are looking for Новолисино
we are looking for Новогорелово
we are looking for Новоселицы
we are looking for Питкяранта
we are looking for Невский округ
we are looking for Ильинский
we are looking for Песочный
we are looking for Лесколово
we are looking for Сясьстрой
we are looking for Никольское
we are looking for Сапёрный
we are looking for Советский
we are looking for Коммунар
we are looking for Лодейное Поле
we are looking for Шлиссельбург
we are looking for Малое Карлино
we are looking for Старая
we are looking for Ленсоветовский
we are looking for Воейково
raj_kumar_gay
we are looking for Плюсса
we are looking for Петрозаводск
we are looking for Псков
we are looking for Боровичи
we are looking for Валдай
we are looking for Пикалево
we are looking for Едрово
we are looking for Чагода
we are looking for Дедовичи
we are looking for Вилга
we are looking for Вяртсиля
we are looking for Ляскеля
we are looking for Подпорожье
we are looking for Новая Вилга
we are looking for Озёрный
we are looking for Старая Русса
we are looking for Псковский район
we are looking for Окуловка
we are looking for Печоры
we are looking for Остров
we are looking for Орел
we are looking for Яжелбицы
we are looking for Выползово
we are looking for Демянск
we are looking for Писковичи
we are looking for Сольцы
we are looking for Федоровщина
we are looking for Парфино
we are looking for Изборск
we are looking for Городище
we are looking for Порхов
we are looking for Череха
we are looking for Ваулино
we are looking for Пряжа
we are looking for Любытино
we are looking for Неелово 2-е
there is no such city found Неелово 2-е
we are looking for Дно
we are looking for Ужесельга
we are looking for Соловьи
we are looking for Рауталахти
we are looking for Бесовец
we are looking for Ладва-Ветка

[{'city': 'Ковалёво',
  'lattitude': 52.68193,
  'longitude': 30.5613,
  'temperature': 7.96,
  'air_quality': 3,
  'mestnost': 146.0,
  'salary': 99884.16666666667,
  'infrastructure': 9},
 {'city': 'Петергоф',
  'lattitude': 59.881847,
  'longitude': 29.912041,
  'temperature': 8,
  'air_quality': 2,
  'mestnost': 24.0,
  'salary': 95962.5,
  'infrastructure': 179},
 {'city': 'Синявино',
  'lattitude': 59.9075049,
  'longitude': 31.0728782,
  'temperature': 7.74,
  'air_quality': 2,
  'mestnost': 18.0,
  'salary': 94792.5,
  'infrastructure': 67},
 {'city': 'Волхов',
  'lattitude': 59.9275868,
  'longitude': 32.3276803,
  'population': 44868,
  'temperature': 8.61,
  'air_quality': 2,
  'mestnost': 35.0,
  'salary': 93874.5,
  'infrastructure': 34},
 {'city': 'Вырица',
  'lattitude': 59.4126621,
  'longitude': 30.3496831,
  'temperature': 7.86,
  'air_quality': 2,
  'mestnost': 62.0,
  'salary': 86397.5,
  'infrastructure': 10},
 {'city': 'Кудрово',
  'lattitude': 59.9083906,
  'longitude': 30.5126078,
  'temperature': 7.79,
  'air_quality': 2,
  'mestnost': 8.0,
  'salary': 118850.0,
  'infrastructure': 500},
 {'city': 'Парголово',
  'lattitude': 60.0837018,
  'longitude': 30.2795673,
  'temperature': 7.56,
  'air_quality': 2,
  'mestnost': 44.0,
  'salary': 96099.0,
  'infrastructure': 500},
 {'city': 'Кронштадт',
  'lattitude': 45.6523093,
  'longitude': 25.6102746,
  'population': 290743,
  'temperature': 9.37,
  'air_quality': 3,
  'mestnost': 571.0,
  'salary': 124422.5,
  'infrastructure': 287},
 {'city': 'Щеглово',
  'lattitude': 55.349564,
  'longitude': 76.564423,
  'temperature': -1.1,
  'air_quality': 3,
  'mestnost': 114.0,
  'salary': 96700.0,
  'infrastructure': 4},
 {'city': 'Посёлок имени Свердлова',
  'lattitude': 59.7963994,
  'longitude': 30.6558175,
  'temperature': 7.8,
  'air_quality': 2,
  'mestnost': 9.0,
  'salary': 84166.66666666667,
  'infrastructure': 500},
 {'city': 'Бугры',
  'lattitude': 58.6840329,
  'longitude': 81.4779906,
  'temperature': 1.17,
  'air_quality': 3,
  'mestnost': 67.0,
  'salary': 88487.5,
  'infrastructure': 4},
 {'city': 'Бокситогорск',
  'lattitude': 59.4729021,
  'longitude': 33.8489952,
  'population': 15249,
  'temperature': 7.2,
  'air_quality': 2,
  'mestnost': 103.0,
  'salary': 91658.475,
  'infrastructure': 9},
 {'city': 'Приладожский',
  'lattitude': 59.875023,
  'longitude': 31.324961,
  'temperature': 7.47,
  'air_quality': 2,
  'mestnost': 13.0,
  'salary': 93875.0,
  'infrastructure': 13},
 {'city': 'Ленинское',
  'lattitude': 48.3646625,
  'longitude': 37.9062824,
  'population': 7705,
  'temperature': 8.54,
  'air_quality': 2,
  'mestnost': 223.0,
  'salary': 114376.57894736843,
  'infrastructure': 85},
 {'city': 'Чудово',
  'lattitude': 59.119539,
  'longitude': 31.6665887,
  'population': 14394,
  'temperature': 8.6,
  'air_quality': 2,
  'mestnost': 32.0,
  'salary': 70663.0,
  'infrastructure': 21},
 {'city': 'Посёлок имени Морозова',
  'lattitude': 59.9739296,
  'longitude': 31.0403667,
  'temperature': 7.59,
  'air_quality': 2,
  'mestnost': 14.0,
  'salary': 77950.0,
  'infrastructure': 60},
 {'city': 'Виллозское городское поселение',
  'lattitude': 59.728073800000004,
  'longitude': 30.193969257633817,
  'temperature': 7.6,
  'air_quality': 2,
  'mestnost': 80.0,
  'salary': 144416.66666666666,
  'infrastructure': 500},
 {'city': 'Тосно',
  'lattitude': 59.5412777,
  'longitude': 30.8773645,
  'population': 37509,
  'temperature': 8.1,
  'air_quality': 2,
  'mestnost': 36.0,
  'salary': 136857.5,
  'infrastructure': 30},
 {'city': 'Новолисино',
  'lattitude': 59.567509,
  'longitude': 30.770937,
  'temperature': 7.91,
  'air_quality': 2,
  'mestnost': 59.0,
  'salary': 107673.0,
  'infrastructure': 49},
 {'city': 'Новогорелово',
  'lattitude': 59.7901627,
  'longitude': 30.1645801,
  'temperature': 7.98,
  'air_quality': 2,
  'mestnost': 25.0,
  'salary': 112493.95,
  'infrastructure': 500},
 {'city': 'Новоселицы',
  'lattitude': 58.5231358,
  'longitude': 31.6973851,
  'temperature': 7.92,
  'air_quality': 2,
  'mestnost': 32.0,
  'salary': 87300.0,
  'infrastructure': 7},
 {'city': 'Питкяранта',
  'lattitude': 61.5717807,
  'longitude': 31.4744211,
  'temperature': 4.49,
  'air_quality': 2,
  'mestnost': 25.0,
  'salary': 230555.55555555556,
  'infrastructure': 10},
 {'city': 'Невский округ',
  'lattitude': 59.90975275,
  'longitude': 30.449643631224916,
  'temperature': 7.79,
  'air_quality': 2,
  'mestnost': 17.0,
  'salary': 169475.0,
  'infrastructure': 500},
 {'city': 'Ильинский',
  'lattitude': 55.6180826,
  'longitude': 38.1002947,
  'temperature': 5.87,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 119225.0,
  'infrastructure': 500},
 {'city': 'Песочный',
  'lattitude': 60.1211791,
  'longitude': 30.1637647,
  'temperature': 7.65,
  'air_quality': 2,
  'mestnost': 32.0,
  'salary': 87460.52631578948,
  'infrastructure': 500},
 {'city': 'Лесколово',
  'lattitude': 60.272068,
  'longitude': 30.462023,
  'temperature': 6.67,
  'air_quality': 2,
  'mestnost': 92.0,
  'salary': 67365.0,
  'infrastructure': 36},
 {'city': 'Сясьстрой',
  'lattitude': 60.1397073,
  'longitude': 32.5637502,
  'population': 12824,
  'temperature': 5.99,
  'air_quality': 2,
  'mestnost': 18.0,
  'salary': 73947.5,
  'infrastructure': 22},
 {'city': 'Никольское',
  'lattitude': 59.7034799,
  'longitude': 30.7861084,
  'population': 22286,
  'temperature': 8.11,
  'air_quality': 2,
  'mestnost': 27.0,
  'salary': 104632.5,
  'infrastructure': 173},
 {'city': 'Сапёрный',
  'lattitude': 59.7780033,
  'longitude': 30.6905386,
  'temperature': 7.78,
  'air_quality': 2,
  'mestnost': 13.0,
  'salary': 100937.5,
  'infrastructure': 300},
 {'city': 'Советский',
  'lattitude': 61.362099,
  'longitude': 63.57354,
  'temperature': 0.03,
  'air_quality': 2,
  'mestnost': 117.0,
  'salary': 69177.33333333333,
  'infrastructure': 103},
 {'city': 'Коммунар',
  'lattitude': 59.6221955,
  'longitude': 30.3919223,
  'population': 22055,
  'temperature': 7.74,
  'air_quality': 2,
  'mestnost': 61.0,
  'salary': 93544.0,
  'infrastructure': 169},
 {'city': 'Лодейное Поле',
  'lattitude': 60.7339323,
  'longitude': 33.5457731,
  'population': 19458,
  'temperature': 5.26,
  'air_quality': 2,
  'mestnost': 19.0,
  'salary': 96262.25,
  'infrastructure': 39},
 {'city': 'Шлиссельбург',
  'lattitude': 59.940431,
  'longitude': 31.0336955,
  'population': 14763,
  'temperature': 7.67,
  'air_quality': 2,
  'mestnost': 12.0,
  'salary': 115200.0,
  'infrastructure': 60},
 {'city': 'Малое Карлино',
  'lattitude': 59.7232765,
  'longitude': 30.2682737,
  'temperature': 7.48,
  'air_quality': 2,
  'mestnost': 101.0,
  'salary': 90007.5,
  'infrastructure': 500},
 {'city': 'Старая',
  'lattitude': 60.4432545,
  'longitude': 46.9289159,
  'temperature': 1.93,
  'air_quality': 2,
  'mestnost': 92.0,
  'salary': 119605.26315789473,
  'infrastructure': 11},
 {'city': 'Ленсоветовский',
  'lattitude': 59.75904245,
  'longitude': 30.470272784273654,
  'temperature': 8.02,
  'air_quality': 2,
  'mestnost': 16.0,
  'salary': 101550.0,
  'infrastructure': 500},
 {'city': 'Воейково',
  'lattitude': 53.1258093,
  'longitude': 44.7089694,
  'temperature': 1.21,
  'air_quality': 3,
  'salary': 91346.25,
  'infrastructure': 11},
 {'city': 'Плюсса',
  'lattitude': 58.420612,
  'longitude': 29.3706,
  'temperature': 9,
  'air_quality': 2,
  'mestnost': 72.0,
  'salary': 51500.0,
  'infrastructure': 6},
 {'city': 'Петрозаводск',
  'lattitude': 61.790039,
  'longitude': 34.390007,
  'population': 278551,
  'temperature': 8.05,
  'air_quality': 2,
  'mestnost': 36.0,
  'salary': 53460.0,
  'infrastructure': 194},
 {'city': 'Псков',
  'lattitude': 57.8173923,
  'longitude': 28.3343465,
  'population': 209840,
  'temperature': 10.99,
  'air_quality': 3,
  'mestnost': 51.0,
  'salary': 60032.5,
  'infrastructure': 192},
 {'city': 'Боровичи',
  'lattitude': 58.389009,
  'longitude': 33.9068275,
  'population': 50144,
  'temperature': 7.48,
  'air_quality': 2,
  'mestnost': 86.0,
  'salary': 86175.0,
  'infrastructure': 41},
 {'city': 'Валдай',
  'lattitude': 57.9791414,
  'longitude': 33.2537994,
  'population': 14379,
  'temperature': 6.52,
  'air_quality': 2,
  'mestnost': 211.0,
  'salary': 130184.21052631579,
  'infrastructure': 16},
 {'city': 'Пикалево',
  'lattitude': 59.5129787,
  'longitude': 34.1773573,
  'temperature': 5.53,
  'air_quality': 2,
  'mestnost': 182.0,
  'salary': 86070.85294117648,
  'infrastructure': 22},
 {'city': 'Едрово',
  'lattitude': 57.914154,
  'longitude': 33.624352,
  'temperature': 6.73,
  'air_quality': 2,
  'mestnost': 201.0,
  'salary': 150000.0,
  'infrastructure': 17},
 {'city': 'Чагода',
  'lattitude': 59.16383,
  'longitude': 35.329369,
  'temperature': 5.57,
  'air_quality': 2,
  'mestnost': 133.0,
  'salary': 68900.0,
  'infrastructure': 8},
 {'city': 'Дедовичи',
  'lattitude': 57.551205,
  'longitude': 29.945297,
  'temperature': 8.65,
  'air_quality': 2,
  'mestnost': 88.0,
  'salary': 57480.0,
  'infrastructure': 10},
 {'city': 'Вилга',
  'lattitude': 61.8185996,
  'longitude': 34.087038,
  'temperature': 7.75,
  'air_quality': 2,
  'mestnost': 78.0,
  'salary': 54000.0,
  'infrastructure': 146},
 {'city': 'Вяртсиля',
  'lattitude': 62.176053,
  'longitude': 30.6961678,
  'temperature': 7.54,
  'air_quality': 2,
  'mestnost': 82.0,
  'salary': 320000.0,
  'infrastructure': 6},
 {'city': 'Ляскеля',
  'lattitude': 61.762192,
  'longitude': 31.007627,
  'temperature': 5.06,
  'air_quality': 2,
  'mestnost': 28.0,
  'salary': 100000.0,
  'infrastructure': 3},
 {'city': 'Подпорожье',
  'lattitude': 60.914291,
  'longitude': 34.162354,
  'population': 17270,
  'temperature': 5.11,
  'air_quality': 2,
  'mestnost': 65.0,
  'salary': 80710.0,
  'infrastructure': 10},
 {'city': 'Новая Вилга',
  'lattitude': 61.814688,
  'longitude': 34.1616471,
  'temperature': 7.84,
  'air_quality': 2,
  'mestnost': 83.0,
  'salary': 74510.0,
  'infrastructure': 190},
 {'city': 'Озёрный',
  'lattitude': 57.868053,
  'longitude': 33.686657,
  'temperature': 6.87,
  'air_quality': 2,
  'mestnost': 195.0,
  'salary': 133550.0,
  'infrastructure': 18},
 {'city': 'Старая Русса',
  'lattitude': 57.9898923,
  'longitude': 31.3634905,
  'population': 29019,
  'temperature': 9.26,
  'air_quality': 2,
  'mestnost': 34.0,
  'salary': 75520.0,
  'infrastructure': 50},
 {'city': 'Псковский район',
  'lattitude': 58.5065519,
  'longitude': 31.242733,
  'temperature': 8.66,
  'air_quality': 2,
  'mestnost': 25.0,
  'salary': 70235.1,
  'infrastructure': 203},
 {'city': 'Окуловка',
  'lattitude': 58.3740782,
  'longitude': 33.3009383,
  'temperature': 6.74,
  'air_quality': 2,
  'mestnost': 175.0,
  'salary': 128890.0,
  'infrastructure': 24},
 {'city': 'Печоры',
  'lattitude': 57.813305,
  'longitude': 27.608185,
  'population': 9670,
  'temperature': 10.21,
  'air_quality': 3,
  'mestnost': 92.0,
  'salary': 103049.175,
  'infrastructure': 8},
 {'city': 'Остров',
  'lattitude': 57.344631,
  'longitude': 28.357817,
  'population': 20427,
  'temperature': 9.42,
  'air_quality': 3,
  'mestnost': 68.0,
  'salary': 178202.0,
  'infrastructure': 32},
 {'city': 'Орел',
  'lattitude': 52.9685433,
  'longitude': 36.0692477,
  'temperature': 2.99,
  'air_quality': 3,
  'mestnost': 153.0,
  'salary': 71062.5,
  'infrastructure': 179},
 {'city': 'Яжелбицы',
  'lattitude': 58.034077,
  'longitude': 32.968437,
  'temperature': 7.1,
  'air_quality': 2,
  'mestnost': 82.0,
  'salary': 90875.0,
  'infrastructure': 4},
 {'city': 'Выползово',
  'lattitude': 58.3690642,
  'longitude': 42.4730807,
  'temperature': 2.68,
  'air_quality': 2,
  'mestnost': 194.0,
  'salary': 153803.33333333334,
  'infrastructure': 14},
 {'city': 'Демянск',
  'lattitude': 57.6423554,
  'longitude': 32.4646788,
  'population': 20505,
  'temperature': 7.94,
  'air_quality': 2,
  'mestnost': 57.0,
  'salary': 108250.0,
  'infrastructure': 7},
 {'city': 'Писковичи',
  'lattitude': 46.0173296,
  'longitude': 16.0045273,
  'temperature': 13.81,
  'air_quality': 3,
  'mestnost': 251.0,
  'infrastructure': 53},
 {'city': 'Сольцы',
  'lattitude': 58.119003,
  'longitude': 30.309679,
  'temperature': 9.03,
  'air_quality': 2,
  'mestnost': 30.0,
  'salary': 60480.555555555555,
  'infrastructure': 8},
 {'city': 'Федоровщина',
  'lattitude': 57.152378,
  'longitude': 31.966232,
  'temperature': 7.18,
  'air_quality': 2,
  'mestnost': 167.0,
  'salary': 56967.5,
  'infrastructure': 0},
 {'city': 'Парфино',
  'lattitude': 57.9713226,
  'longitude': 31.649848,
  'temperature': 9.06,
  'air_quality': 2,
  'mestnost': 29.0,
  'salary': 91416.66666666667,
  'infrastructure': 3},
 {'city': 'Изборск',
  'lattitude': 57.7103914,
  'longitude': 27.861682,
  'temperature': 10.29,
  'air_quality': 3,
  'mestnost': 80.0,
  'salary': 54945.0,
  'infrastructure': 3},
 {'city': 'Городище',
  'lattitude': 48.810127,
  'longitude': 44.476082,
  'temperature': 8.4,
  'air_quality': 2,
  'mestnost': 85.0,
  'salary': 68280.0,
  'infrastructure': 472},
 {'city': 'Порхов',
  'lattitude': 57.765289,
  'longitude': 29.551878,
  'population': 8743,
  'temperature': 9.04,
  'air_quality': 2,
  'mestnost': 52.0,
  'salary': 85750.0,
  'infrastructure': 12},
 {'city': 'Череха',
  'lattitude': 57.7478983,
  'longitude': 28.3734774,
  'temperature': 10.99,
  'air_quality': 3,
  'mestnost': 45.0,
  'salary': 83873.33333333333,
  'infrastructure': 193},
 {'city': 'Ваулино',
  'lattitude': 57.745361,
  'longitude': 38.999599,
  'temperature': 5.75,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 150000.0,
  'infrastructure': 14},
 {'city': 'Пряжа',
  'lattitude': 46.3372498,
  'longitude': 27.4214433,
  'temperature': 9.96,
  'air_quality': 3,
  'mestnost': 320.0,
  'salary': 86024.75,
  'infrastructure': 1},
 {'city': 'Любытино',
  'lattitude': 58.8142322,
  'longitude': 33.3976972,
  'temperature': 7.49,
  'air_quality': 2,
  'mestnost': 59.0,
  'salary': 43566.666666666664,
  'infrastructure': 5},
 {'city': 'Дно',
  'lattitude': 57.8288277,
  'longitude': 29.9611357,
  'population': 20701,
  'temperature': 8.93,
  'air_quality': 2,
  'mestnost': 69.0,
  'salary': 83081.20588235294,
  'infrastructure': 7},
 {'city': 'Ужесельга',
  'lattitude': 61.723103,
  'longitude': 34.4827,
  'temperature': 7.72,
  'air_quality': 2,
  'mestnost': 93.0,
  'infrastructure': 174},
 {'city': 'Соловьи',
  'lattitude': 57.685852,
  'longitude': 28.325863,
  'temperature': 11.01,
  'air_quality': 3,
  'mestnost': 44.0,
  'salary': 108281.25,
  'infrastructure': 116},
 {'city': 'Рауталахти',
  'lattitude': 61.6234067,
  'longitude': 29.6002317,
  'temperature': 8.82,
  'air_quality': 2,
  'mestnost': 113.0,
  'salary': 57500.0,
  'infrastructure': 6},
 {'city': 'Бесовец',
  'lattitude': 61.865685,
  'longitude': 34.158962,
  'temperature': 8.01,
  'air_quality': 2,
  'mestnost': 42.0,
  'infrastructure': 156},
 {'city': 'Ладва-Ветка',
  'lattitude': 61.362133,
  'longitude': 34.4469318,
  'temperature': 5.78,
  'air_quality': 2,
  'mestnost': 105.0,
  'infrastructure': 0}]

In [ ]:
data3

[{'city': 'Ковалёво',
  'lattitude': 52.68193,
  'longitude': 30.5613,
  'temperature': 7.96,
  'air_quality': 3,
  'mestnost': 146.0,
  'salary': 99884.16666666667,
  'infrastructure': 9},
 {'city': 'Петергоф',
  'lattitude': 59.881847,
  'longitude': 29.912041,
  'temperature': 8,
  'air_quality': 2,
  'mestnost': 24.0,
  'salary': 95962.5,
  'infrastructure': 179},
 {'city': 'Синявино',
  'lattitude': 59.9075049,
  'longitude': 31.0728782,
  'temperature': 7.74,
  'air_quality': 2,
  'mestnost': 18.0,
  'salary': 94792.5,
  'infrastructure': 67},
 {'city': 'Волхов',
  'lattitude': 59.9275868,
  'longitude': 32.3276803,
  'population': 44868,
  'temperature': 8.61,
  'air_quality': 2,
  'mestnost': 35.0,
  'salary': 93874.5,
  'infrastructure': 34},
 {'city': 'Вырица',
  'lattitude': 59.4126621,
  'longitude': 30.3496831,
  'temperature': 7.86,
  'air_quality': 2,
  'mestnost': 62.0,
  'salary': 86397.5,
  'infrastructure': 10},
 {'city': 'Кудрово',
  'lattitude': 59.9083906,
  'longitude': 30.5126078,
  'temperature': 7.79,
  'air_quality': 2,
  'mestnost': 8.0,
  'salary': 118850.0,
  'infrastructure': 500},
 {'city': 'Парголово',
  'lattitude': 60.0837018,
  'longitude': 30.2795673,
  'temperature': 7.56,
  'air_quality': 2,
  'mestnost': 44.0,
  'salary': 96099.0,
  'infrastructure': 500},
 {'city': 'Кронштадт',
  'lattitude': 45.6523093,
  'longitude': 25.6102746,
  'population': 290743,
  'temperature': 9.37,
  'air_quality': 3,
  'mestnost': 571.0,
  'salary': 124422.5,
  'infrastructure': 287},
 {'city': 'Щеглово',
  'lattitude': 55.349564,
  'longitude': 76.564423,
  'temperature': -1.1,
  'air_quality': 3,
  'mestnost': 114.0,
  'salary': 96700.0,
  'infrastructure': 4},
 {'city': 'Посёлок имени Свердлова',
  'lattitude': 59.7963994,
  'longitude': 30.6558175,
  'temperature': 7.8,
  'air_quality': 2,
  'mestnost': 9.0,
  'salary': 84166.66666666667,
  'infrastructure': 500},
 {'city': 'Бугры',
  'lattitude': 58.6840329,
  'longitude': 81.4779906,
  'temperature': 1.17,
  'air_quality': 3,
  'mestnost': 67.0,
  'salary': 88487.5,
  'infrastructure': 4},
 {'city': 'Бокситогорск',
  'lattitude': 59.4729021,
  'longitude': 33.8489952,
  'population': 15249,
  'temperature': 7.2,
  'air_quality': 2,
  'mestnost': 103.0,
  'salary': 91658.475,
  'infrastructure': 9},
 {'city': 'Приладожский',
  'lattitude': 59.875023,
  'longitude': 31.324961,
  'temperature': 7.47,
  'air_quality': 2,
  'mestnost': 13.0,
  'salary': 93875.0,
  'infrastructure': 13},
 {'city': 'Ленинское',
  'lattitude': 48.3646625,
  'longitude': 37.9062824,
  'population': 7705,
  'temperature': 8.54,
  'air_quality': 2,
  'mestnost': 223.0,
  'salary': 114376.57894736843,
  'infrastructure': 85},
 {'city': 'Чудово',
  'lattitude': 59.119539,
  'longitude': 31.6665887,
  'population': 14394,
  'temperature': 8.6,
  'air_quality': 2,
  'mestnost': 32.0,
  'salary': 70663.0,
  'infrastructure': 21},
 {'city': 'Посёлок имени Морозова',
  'lattitude': 59.9739296,
  'longitude': 31.0403667,
  'temperature': 7.59,
  'air_quality': 2,
  'mestnost': 14.0,
  'salary': 77950.0,
  'infrastructure': 60},
 {'city': 'Виллозское городское поселение',
  'lattitude': 59.728073800000004,
  'longitude': 30.193969257633817,
  'temperature': 7.6,
  'air_quality': 2,
  'mestnost': 80.0,
  'salary': 144416.66666666666,
  'infrastructure': 500},
 {'city': 'Тосно',
  'lattitude': 59.5412777,
  'longitude': 30.8773645,
  'population': 37509,
  'temperature': 8.1,
  'air_quality': 2,
  'mestnost': 36.0,
  'salary': 136857.5,
  'infrastructure': 30},
 {'city': 'Новолисино',
  'lattitude': 59.567509,
  'longitude': 30.770937,
  'temperature': 7.91,
  'air_quality': 2,
  'mestnost': 59.0,
  'salary': 107673.0,
  'infrastructure': 49},
 {'city': 'Новогорелово',
  'lattitude': 59.7901627,
  'longitude': 30.1645801,
  'temperature': 7.98,
  'air_quality': 2,
  'mestnost': 25.0,
  'salary': 112493.95,
  'infrastructure': 500},
 {'city': 'Новоселицы',
  'lattitude': 58.5231358,
  'longitude': 31.6973851,
  'temperature': 7.92,
  'air_quality': 2,
  'mestnost': 32.0,
  'salary': 87300.0,
  'infrastructure': 7},
 {'city': 'Питкяранта',
  'lattitude': 61.5717807,
  'longitude': 31.4744211,
  'temperature': 4.49,
  'air_quality': 2,
  'mestnost': 25.0,
  'salary': 230555.55555555556,
  'infrastructure': 10},
 {'city': 'Невский округ',
  'lattitude': 59.90975275,
  'longitude': 30.449643631224916,
  'temperature': 7.79,
  'air_quality': 2,
  'mestnost': 17.0,
  'salary': 169475.0,
  'infrastructure': 500},
 {'city': 'Ильинский',
  'lattitude': 55.6180826,
  'longitude': 38.1002947,
  'temperature': 5.87,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 119225.0,
  'infrastructure': 500},
 {'city': 'Песочный',
  'lattitude': 60.1211791,
  'longitude': 30.1637647,
  'temperature': 7.65,
  'air_quality': 2,
  'mestnost': 32.0,
  'salary': 87460.52631578948,
  'infrastructure': 500},
 {'city': 'Лесколово',
  'lattitude': 60.272068,
  'longitude': 30.462023,
  'temperature': 6.67,
  'air_quality': 2,
  'mestnost': 92.0,
  'salary': 67365.0,
  'infrastructure': 36},
 {'city': 'Сясьстрой',
  'lattitude': 60.1397073,
  'longitude': 32.5637502,
  'population': 12824,
  'temperature': 5.99,
  'air_quality': 2,
  'mestnost': 18.0,
  'salary': 73947.5,
  'infrastructure': 22},
 {'city': 'Никольское',
  'lattitude': 59.7034799,
  'longitude': 30.7861084,
  'population': 22286,
  'temperature': 8.11,
  'air_quality': 2,
  'mestnost': 27.0,
  'salary': 104632.5,
  'infrastructure': 173},
 {'city': 'Сапёрный',
  'lattitude': 59.7780033,
  'longitude': 30.6905386,
  'temperature': 7.78,
  'air_quality': 2,
  'mestnost': 13.0,
  'salary': 100937.5,
  'infrastructure': 300},
 {'city': 'Советский',
  'lattitude': 61.362099,
  'longitude': 63.57354,
  'temperature': 0.03,
  'air_quality': 2,
  'mestnost': 117.0,
  'salary': 69177.33333333333,
  'infrastructure': 103},
 {'city': 'Коммунар',
  'lattitude': 59.6221955,
  'longitude': 30.3919223,
  'population': 22055,
  'temperature': 7.74,
  'air_quality': 2,
  'mestnost': 61.0,
  'salary': 93544.0,
  'infrastructure': 169},
 {'city': 'Лодейное Поле',
  'lattitude': 60.7339323,
  'longitude': 33.5457731,
  'population': 19458,
  'temperature': 5.26,
  'air_quality': 2,
  'mestnost': 19.0,
  'salary': 96262.25,
  'infrastructure': 39},
 {'city': 'Шлиссельбург',
  'lattitude': 59.940431,
  'longitude': 31.0336955,
  'population': 14763,
  'temperature': 7.67,
  'air_quality': 2,
  'mestnost': 12.0,
  'salary': 115200.0,
  'infrastructure': 60},
 {'city': 'Малое Карлино',
  'lattitude': 59.7232765,
  'longitude': 30.2682737,
  'temperature': 7.48,
  'air_quality': 2,
  'mestnost': 101.0,
  'salary': 90007.5,
  'infrastructure': 500},
 {'city': 'Старая',
  'lattitude': 60.4432545,
  'longitude': 46.9289159,
  'temperature': 1.93,
  'air_quality': 2,
  'mestnost': 92.0,
  'salary': 119605.26315789473,
  'infrastructure': 11},
 {'city': 'Ленсоветовский',
  'lattitude': 59.75904245,
  'longitude': 30.470272784273654,
  'temperature': 8.02,
  'air_quality': 2,
  'mestnost': 16.0,
  'salary': 101550.0,
  'infrastructure': 500},
 {'city': 'Воейково',
  'lattitude': 53.1258093,
  'longitude': 44.7089694,
  'temperature': 1.21,
  'air_quality': 3,
  'salary': 91346.25,
  'infrastructure': 11},
 {'city': 'Плюсса',
  'lattitude': 58.420612,
  'longitude': 29.3706,
  'temperature': 9,
  'air_quality': 2,
  'mestnost': 72.0,
  'salary': 51500.0,
  'infrastructure': 6},
 {'city': 'Петрозаводск',
  'lattitude': 61.790039,
  'longitude': 34.390007,
  'population': 278551,
  'temperature': 8.05,
  'air_quality': 2,
  'mestnost': 36.0,
  'salary': 53460.0,
  'infrastructure': 194},
 {'city': 'Псков',
  'lattitude': 57.8173923,
  'longitude': 28.3343465,
  'population': 209840,
  'temperature': 10.99,
  'air_quality': 3,
  'mestnost': 51.0,
  'salary': 60032.5,
  'infrastructure': 192},
 {'city': 'Боровичи',
  'lattitude': 58.389009,
  'longitude': 33.9068275,
  'population': 50144,
  'temperature': 7.48,
  'air_quality': 2,
  'mestnost': 86.0,
  'salary': 86175.0,
  'infrastructure': 41},
 {'city': 'Валдай',
  'lattitude': 57.9791414,
  'longitude': 33.2537994,
  'population': 14379,
  'temperature': 6.52,
  'air_quality': 2,
  'mestnost': 211.0,
  'salary': 130184.21052631579,
  'infrastructure': 16},
 {'city': 'Пикалево',
  'lattitude': 59.5129787,
  'longitude': 34.1773573,
  'temperature': 5.53,
  'air_quality': 2,
  'mestnost': 182.0,
  'salary': 86070.85294117648,
  'infrastructure': 22},
 {'city': 'Едрово',
  'lattitude': 57.914154,
  'longitude': 33.624352,
  'temperature': 6.73,
  'air_quality': 2,
  'mestnost': 201.0,
  'salary': 150000.0,
  'infrastructure': 17},
 {'city': 'Чагода',
  'lattitude': 59.16383,
  'longitude': 35.329369,
  'temperature': 5.57,
  'air_quality': 2,
  'mestnost': 133.0,
  'salary': 68900.0,
  'infrastructure': 8},
 {'city': 'Дедовичи',
  'lattitude': 57.551205,
  'longitude': 29.945297,
  'temperature': 8.65,
  'air_quality': 2,
  'mestnost': 88.0,
  'salary': 57480.0,
  'infrastructure': 10},
 {'city': 'Вилга',
  'lattitude': 61.8185996,
  'longitude': 34.087038,
  'temperature': 7.75,
  'air_quality': 2,
  'mestnost': 78.0,
  'salary': 54000.0,
  'infrastructure': 146},
 {'city': 'Вяртсиля',
  'lattitude': 62.176053,
  'longitude': 30.6961678,
  'temperature': 7.54,
  'air_quality': 2,
  'mestnost': 82.0,
  'salary': 320000.0,
  'infrastructure': 6},
 {'city': 'Ляскеля',
  'lattitude': 61.762192,
  'longitude': 31.007627,
  'temperature': 5.06,
  'air_quality': 2,
  'mestnost': 28.0,
  'salary': 100000.0,
  'infrastructure': 3},
 {'city': 'Подпорожье',
  'lattitude': 60.914291,
  'longitude': 34.162354,
  'population': 17270,
  'temperature': 5.11,
  'air_quality': 2,
  'mestnost': 65.0,
  'salary': 80710.0,
  'infrastructure': 10},
 {'city': 'Новая Вилга',
  'lattitude': 61.814688,
  'longitude': 34.1616471,
  'temperature': 7.84,
  'air_quality': 2,
  'mestnost': 83.0,
  'salary': 74510.0,
  'infrastructure': 190},
 {'city': 'Озёрный',
  'lattitude': 57.868053,
  'longitude': 33.686657,
  'temperature': 6.87,
  'air_quality': 2,
  'mestnost': 195.0,
  'salary': 133550.0,
  'infrastructure': 18},
 {'city': 'Старая Русса',
  'lattitude': 57.9898923,
  'longitude': 31.3634905,
  'population': 29019,
  'temperature': 9.26,
  'air_quality': 2,
  'mestnost': 34.0,
  'salary': 75520.0,
  'infrastructure': 50},
 {'city': 'Псковский район',
  'lattitude': 58.5065519,
  'longitude': 31.242733,
  'temperature': 8.66,
  'air_quality': 2,
  'mestnost': 25.0,
  'salary': 70235.1,
  'infrastructure': 203},
 {'city': 'Окуловка',
  'lattitude': 58.3740782,
  'longitude': 33.3009383,
  'temperature': 6.74,
  'air_quality': 2,
  'mestnost': 175.0,
  'salary': 128890.0,
  'infrastructure': 24},
 {'city': 'Печоры',
  'lattitude': 57.813305,
  'longitude': 27.608185,
  'population': 9670,
  'temperature': 10.21,
  'air_quality': 3,
  'mestnost': 92.0,
  'salary': 103049.175,
  'infrastructure': 8},
 {'city': 'Остров',
  'lattitude': 57.344631,
  'longitude': 28.357817,
  'population': 20427,
  'temperature': 9.42,
  'air_quality': 3,
  'mestnost': 68.0,
  'salary': 178202.0,
  'infrastructure': 32},
 {'city': 'Орел',
  'lattitude': 52.9685433,
  'longitude': 36.0692477,
  'temperature': 2.99,
  'air_quality': 3,
  'mestnost': 153.0,
  'salary': 71062.5,
  'infrastructure': 179},
 {'city': 'Яжелбицы',
  'lattitude': 58.034077,
  'longitude': 32.968437,
  'temperature': 7.1,
  'air_quality': 2,
  'mestnost': 82.0,
  'salary': 90875.0,
  'infrastructure': 4},
 {'city': 'Выползово',
  'lattitude': 58.3690642,
  'longitude': 42.4730807,
  'temperature': 2.68,
  'air_quality': 2,
  'mestnost': 194.0,
  'salary': 153803.33333333334,
  'infrastructure': 14},
 {'city': 'Демянск',
  'lattitude': 57.6423554,
  'longitude': 32.4646788,
  'population': 20505,
  'temperature': 7.94,
  'air_quality': 2,
  'mestnost': 57.0,
  'salary': 108250.0,
  'infrastructure': 7},
 {'city': 'Писковичи',
  'lattitude': 46.0173296,
  'longitude': 16.0045273,
  'temperature': 13.81,
  'air_quality': 3,
  'mestnost': 251.0,
  'infrastructure': 53},
 {'city': 'Сольцы',
  'lattitude': 58.119003,
  'longitude': 30.309679,
  'temperature': 9.03,
  'air_quality': 2,
  'mestnost': 30.0,
  'salary': 60480.555555555555,
  'infrastructure': 8},
 {'city': 'Федоровщина',
  'lattitude': 57.152378,
  'longitude': 31.966232,
  'temperature': 7.18,
  'air_quality': 2,
  'mestnost': 167.0,
  'salary': 56967.5,
  'infrastructure': 0},
 {'city': 'Парфино',
  'lattitude': 57.9713226,
  'longitude': 31.649848,
  'temperature': 9.06,
  'air_quality': 2,
  'mestnost': 29.0,
  'salary': 91416.66666666667,
  'infrastructure': 3},
 {'city': 'Изборск',
  'lattitude': 57.7103914,
  'longitude': 27.861682,
  'temperature': 10.29,
  'air_quality': 3,
  'mestnost': 80.0,
  'salary': 54945.0,
  'infrastructure': 3},
 {'city': 'Городище',
  'lattitude': 48.810127,
  'longitude': 44.476082,
  'temperature': 8.4,
  'air_quality': 2,
  'mestnost': 85.0,
  'salary': 68280.0,
  'infrastructure': 472},
 {'city': 'Порхов',
  'lattitude': 57.765289,
  'longitude': 29.551878,
  'population': 8743,
  'temperature': 9.04,
  'air_quality': 2,
  'mestnost': 52.0,
  'salary': 85750.0,
  'infrastructure': 12},
 {'city': 'Череха',
  'lattitude': 57.7478983,
  'longitude': 28.3734774,
  'temperature': 10.99,
  'air_quality': 3,
  'mestnost': 45.0,
  'salary': 83873.33333333333,
  'infrastructure': 193},
 {'city': 'Ваулино',
  'lattitude': 57.745361,
  'longitude': 38.999599,
  'temperature': 5.75,
  'air_quality': 2,
  'mestnost': 136.0,
  'salary': 150000.0,
  'infrastructure': 14},
 {'city': 'Пряжа',
  'lattitude': 46.3372498,
  'longitude': 27.4214433,
  'temperature': 9.96,
  'air_quality': 3,
  'mestnost': 320.0,
  'salary': 86024.75,
  'infrastructure': 1},
 {'city': 'Любытино',
  'lattitude': 58.8142322,
  'longitude': 33.3976972,
  'temperature': 7.49,
  'air_quality': 2,
  'mestnost': 59.0,
  'salary': 43566.666666666664,
  'infrastructure': 5},
 {'city': 'Дно',
  'lattitude': 57.8288277,
  'longitude': 29.9611357,
  'population': 20701,
  'temperature': 8.93,
  'air_quality': 2,
  'mestnost': 69.0,
  'salary': 83081.20588235294,
  'infrastructure': 7},
 {'city': 'Ужесельга',
  'lattitude': 61.723103,
  'longitude': 34.4827,
  'temperature': 7.72,
  'air_quality': 2,
  'mestnost': 93.0,
  'infrastructure': 174},
 {'city': 'Соловьи',
  'lattitude': 57.685852,
  'longitude': 28.325863,
  'temperature': 11.01,
  'air_quality': 3,
  'mestnost': 44.0,
  'salary': 108281.25,
  'infrastructure': 116},
 {'city': 'Рауталахти',
  'lattitude': 61.6234067,
  'longitude': 29.6002317,
  'temperature': 8.82,
  'air_quality': 2,
  'mestnost': 113.0,
  'salary': 57500.0,
  'infrastructure': 6},
 {'city': 'Бесовец',
  'lattitude': 61.865685,
  'longitude': 34.158962,
  'temperature': 8.01,
  'air_quality': 2,
  'mestnost': 42.0,
  'infrastructure': 156},
 {'city': 'Ладва-Ветка',
  'lattitude': 61.362133,
  'longitude': 34.4469318,
  'temperature': 5.78,
  'air_quality': 2,
  'mestnost': 105.0,
  'infrastructure': 0}]

In [ ]:
pd.DataFrame(data3).to_csv('data4.csv')

In [ ]:
test_url = 'https://api.api-ninjas.com/v1/elevation?lat=55.75&lon=37.61'

res = requests.get(test_url, headers={'X-Api-Key': ninja_API})

print(f"Статус ответа: {res.status_code}")
print(f"Текст ошибки: {res.text}")

In [ ]:
res_city = requests.get('https://api.api-ninjas.com/v1/city?name=Moscow', headers={'X-Api-Key': ninja_API})

print(f"Статус City: {res_city.status_code}")
print(f"Ответ City: {res_city.text}")

In [ ]:
data1_f = pd.read_csv('data1.csv')
data2_f = pd.read_csv('data2.csv')
data3_f = pd.read_csv('data3.csv')

In [ ]:
data_f = pd.concat([data1_f, data2_f, data3_f], ignore_index=True)

In [ ]:
data1_f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      157 non-null    int64
 1   city            157 non-null    object
 2   lattitude       157 non-null    float64
 3   longitude       157 non-null    float64
 4   population      82 non-null     float64
 5   temperature     157 non-null    float64
 6   air_quality     157 non-null    int64
 7   mestnost        156 non-null    float64
 8   salary          156 non-null    float64
 9   infrastructure  157 non-null    int64
dtypes: float64(6), int64(3), object(1)
memory usage: 12.4+ KB

In [ ]:
final = pd.DataFrame(data_f)
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      540 non-null    int64
 1   city            540 non-null    object
 2   lattitude       540 non-null    float64
 3   longitude       540 non-null    float64
 4   population      213 non-null    float64
 5   temperature     540 non-null    float64
 6   air_quality     540 non-null    int64
 7   mestnost        530 non-null    float64
 8   salary          519 non-null    float64
 9   infrastructure  540 non-null    int64
dtypes: float64(6), int64(3), object(1)
memory usage: 42.3+ KB

In [ ]:
final

,Unnamed: 0,city,lattitude,longitude,population,temperature,air_quality,mestnost,salary,infrastructure
0,0,Москва,55.750446,37.617494,17125000.0,7.49,2,156.0,362722.15,500
1,1,Немчиновка,55.720842,37.366631,NaN,7.96,2,172.0,135977.15,500
2,2,Химки,55.891729,37.439699,244668.0,8.01,2,186.0,107355.00,500
3,3,Балашиха,55.803623,37.964649,450771.0,7.77,2,166.0,104085.00,500
4,4,Пушкино,59.722256,30.415731,105479.0,7.84,2,44.0,99132.50,500
...,...,...,...,...,...,...,...,...,...,...
535,73,Ужесельга,61.723103,34.482700,NaN,7.72,2,93.0,NaN,174
536,74,Соловьи,57.685852,28.325863,NaN,11.01,3,44.0,108281.25,116
537,75,Рауталахти,61.623407,29.600232,NaN,8.82,2,113.0,57500.00,6
538,76,Бесовец,61.865685,34.158962,NaN,8.01,2,42.0,NaN,156
539,77,Ладва-Ветка,61.362133,34.446932,NaN,5.78,2,105.0,NaN,0

In [ ]:
final.to_csv('final_API_bullshit.csv')

In [ ]:
merged = df.merge(final, on='city', how='left')
merged

,name,price,year,mileage,specs,city,seller,link,Unnamed: 0,lattitude,longitude,population,temperature,air_quality,mestnost,salary,infrastructure
0,Skoda Octavia IV (A8),2070000,2022,49900,"['1.4 л, 150 л.с., бензин', 'Лифтбек', 'Передн...",Москва,GROMOV IMPORT,https://auto.ru/cars/used/sale/skoda/octavia/1...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0
1,Hyundai Solaris II,953700,2018,158735,"['1.6 л, 123 л.с., бензин', 'Седан', 'Передний...",Москва,АО Банк Инго,https://auto.ru/cars/used/sale/hyundai/solaris...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0
2,Mercedes-Benz V-Класс Extra Long 300 d экстра ...,46850000,2024,100,"['2.0 л, 237 л.с., дизель', 'Минивэн', 'Полный...",Москва,А1 АВТО,https://auto.ru/cars/used/sale/mercedes/v_klas...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0
3,BMW X5 48i II (E70),550000,2007,220000,"['4.8 л, 355 л.с., бензин', 'Внедорожник 5 дв....",Москва,Irvineflora,https://auto.ru/cars/used/sale/bmw/x5/11018933...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0
4,Lada (ВАЗ) Kalina I,200000,2006,150000,"['1.6 л, 81 л.с., бензин', 'Седан', 'Передний ...",Москва,петр л.,https://auto.ru/cars/used/sale/vaz/kalina/1131...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12624,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),2021400,2026,_,"['1.8 л, 122 л.с., бензин', 'Универсал 5 дв.',...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/24069...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0
12625,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),1890000,2026,_,"['1.6 л, 106 л.с., бензин', 'Универсал 5 дв.',...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/23628...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0
12626,Lada (ВАЗ) Largus I Рестайлинг,1341600,2026,_,"['1.6 л, 90 л.с., бензин', 'Универсал 5 дв.', ...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/largus/2274...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0
12627,Volkswagen Tiguan Allspace II Рестайлинг,2742000,2022,34000,"['1.5 л, 150 л.с., бензин', 'Внедорожник 5 дв....",Псков,Станислав Игоревич,https://auto.ru/cars/used/sale/volkswagen/tigu...,39.0,57.817392,28.334346,209840.0,10.99,3.0,51.0,60032.50,192.0
12628,Lada (ВАЗ) Granta I Рестайлинг,1048000,2026,_,"['1.6 л, 106 л.с., бензин', 'Седан', 'Передний...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/granta/2137...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0

In [ ]:
merged.to_csv('merged_API_and_scraping.csv')

In [ ]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12629 entries, 0 to 12628
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            12629 non-null  object
 1   price           12629 non-null  int64
 2   year            12629 non-null  int64
 3   mileage         12629 non-null  object
 4   specs           12629 non-null  object
 5   city            12629 non-null  object
 6   seller          12629 non-null  object
 7   link            12629 non-null  object
 8   Unnamed: 0      12595 non-null  float64
 9   lattitude       12595 non-null  float64
 10  longitude       12595 non-null  float64
 11  population      11678 non-null  float64
 12  temperature     12595 non-null  float64
 13  air_quality     12595 non-null  float64
 14  mestnost        12506 non-null  float64
 15  salary          12563 non-null  float64
 16  infrastructure  12595 non-null  float64
dtypes: float64(9), int64(2), object(6)
memory usage: 1.6+ MB

In [ ]:
merged[['engine', 'class', 'drive', 'gearbox']] = merged['specs'].str.strip("'[]").str.split("', '", expand=True)
merged = merged.drop(columns=['specs'])

KeyError: 'specs'

In [ ]:
merged

,name,price,year,mileage,city,seller,link,Unnamed: 0,lattitude,longitude,population,temperature,air_quality,mestnost,salary,infrastructure,engine,class,drive,gearbox
0,Skoda Octavia IV (A8),2070000,2022,49900,Москва,GROMOV IMPORT,https://auto.ru/cars/used/sale/skoda/octavia/1...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0,"1.4 л, 150 л.с., бензин",Лифтбек,Передний привод,Автомат
1,Hyundai Solaris II,953700,2018,158735,Москва,АО Банк Инго,https://auto.ru/cars/used/sale/hyundai/solaris...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0,"1.6 л, 123 л.с., бензин",Седан,Передний привод,Автомат
2,Mercedes-Benz V-Класс Extra Long 300 d экстра ...,46850000,2024,100,Москва,А1 АВТО,https://auto.ru/cars/used/sale/mercedes/v_klas...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0,"2.0 л, 237 л.с., дизель",Минивэн,Полный привод,Автомат
3,BMW X5 48i II (E70),550000,2007,220000,Москва,Irvineflora,https://auto.ru/cars/used/sale/bmw/x5/11018933...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0,"4.8 л, 355 л.с., бензин",Внедорожник 5 дв.,Полный привод,Автомат
4,Lada (ВАЗ) Kalina I,200000,2006,150000,Москва,петр л.,https://auto.ru/cars/used/sale/vaz/kalina/1131...,0.0,55.750446,37.617494,17125000.0,7.49,2.0,156.0,362722.15,500.0,"1.6 л, 81 л.с., бензин",Седан,Передний привод,Механика
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12624,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),2021400,2026,_,Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/24069...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0,"1.8 л, 122 л.с., бензин",Универсал 5 дв.,Передний привод,Механика
12625,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),1890000,2026,_,Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/23628...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0,"1.6 л, 106 л.с., бензин",Универсал 5 дв.,Передний привод,Механика
12626,Lada (ВАЗ) Largus I Рестайлинг,1341600,2026,_,Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/largus/2274...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0,"1.6 л, 90 л.с., бензин",Универсал 5 дв.,Передний привод,Механика
12627,Volkswagen Tiguan Allspace II Рестайлинг,2742000,2022,34000,Псков,Станислав Игоревич,https://auto.ru/cars/used/sale/volkswagen/tigu...,39.0,57.817392,28.334346,209840.0,10.99,3.0,51.0,60032.50,192.0,"1.5 л, 150 л.с., бензин",Внедорожник 5 дв.,Передний привод,Механика
12628,Lada (ВАЗ) Granta I Рестайлинг,1048000,2026,_,Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/granta/2137...,38.0,61.790039,34.390007,278551.0,8.05,2.0,36.0,53460.00,194.0,"1.6 л, 106 л.с., бензин",Седан,Передний привод,Механика

In [ ]:
merged.to_csv('updated_merge.csv')

In [ ]:
merged_logs = df.merge(new, on='city', how='left')
merged_logs

,name,price,year,mileage,specs,city,seller,link,lattitude,longitude,population,temperature,air_quality,mestnost,salary,infrastructure
0,Skoda Octavia IV (A8),2070000,2022,49900,"['1.4 л, 150 л.с., бензин', 'Лифтбек', 'Передн...",Москва,GROMOV IMPORT,https://auto.ru/cars/used/sale/skoda/octavia/1...,55.750446,37.617494,17125000.0,11.72,2.0,156.0,375012.5,500.0
1,Hyundai Solaris II,953700,2018,158735,"['1.6 л, 123 л.с., бензин', 'Седан', 'Передний...",Москва,АО Банк Инго,https://auto.ru/cars/used/sale/hyundai/solaris...,55.750446,37.617494,17125000.0,11.72,2.0,156.0,375012.5,500.0
2,Mercedes-Benz V-Класс Extra Long 300 d экстра ...,46850000,2024,100,"['2.0 л, 237 л.с., дизель', 'Минивэн', 'Полный...",Москва,А1 АВТО,https://auto.ru/cars/used/sale/mercedes/v_klas...,55.750446,37.617494,17125000.0,11.72,2.0,156.0,375012.5,500.0
3,BMW X5 48i II (E70),550000,2007,220000,"['4.8 л, 355 л.с., бензин', 'Внедорожник 5 дв....",Москва,Irvineflora,https://auto.ru/cars/used/sale/bmw/x5/11018933...,55.750446,37.617494,17125000.0,11.72,2.0,156.0,375012.5,500.0
4,Lada (ВАЗ) Kalina I,200000,2006,150000,"['1.6 л, 81 л.с., бензин', 'Седан', 'Передний ...",Москва,петр л.,https://auto.ru/cars/used/sale/vaz/kalina/1131...,55.750446,37.617494,17125000.0,11.72,2.0,156.0,375012.5,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12623,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),2021400,2026,_,"['1.8 л, 122 л.с., бензин', 'Универсал 5 дв.',...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/24069...,61.790039,34.390007,NaN,7.33,2.0,36.0,50987.0,194.0
12624,Lada (ВАЗ) Vesta SW Cross I Рестайлинг (NG),1890000,2026,_,"['1.6 л, 106 л.с., бензин', 'Универсал 5 дв.',...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/vesta/23628...,61.790039,34.390007,NaN,7.33,2.0,36.0,50987.0,194.0
12625,Lada (ВАЗ) Largus I Рестайлинг,1341600,2026,_,"['1.6 л, 90 л.с., бензин', 'Универсал 5 дв.', ...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/largus/2274...,61.790039,34.390007,NaN,7.33,2.0,36.0,50987.0,194.0
12626,Volkswagen Tiguan Allspace II Рестайлинг,2742000,2022,34000,"['1.5 л, 150 л.с., бензин', 'Внедорожник 5 дв....",Псков,Станислав Игоревич,https://auto.ru/cars/used/sale/volkswagen/tigu...,57.817392,28.334346,NaN,10.93,2.0,51.0,64282.5,192.0
12627,Lada (ВАЗ) Granta I Рестайлинг,1048000,2026,_,"['1.6 л, 106 л.с., бензин', 'Седан', 'Передний...",Петрозаводск,Петрозаводск-Лада,https://auto.ru/cars/new/group/vaz/granta/2137...,61.790039,34.390007,NaN,7.33,2.0,36.0,50987.0,194.0

In [ ]:
merged_logs[['engine', 'class', 'drive', 'gearbox']] = merged_logs['specs'].str.strip("'[]").str.split("', '", expand=True)
merged_logs = merged_logs.drop(columns=['specs'])

In [ ]:
merged_logs.to_csv('updated_merge.csv')